---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-post-install
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./common/keycloak/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: '25.2.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1h
  releaseName: keycloak
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      repository: keycloak/keycloak
      tag: 26.3.3
    podLabels:
      sidecar.istio.io/inject: "true"
    production: true
    proxyHeaders: "X-Forwarded-For"
    httpEnabled: true
    auth:
      adminUser: admin
      existingSecret: keycloak-secret
      passwordSecretKey: password
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    extraEnvVars:
    - name: KEYCLOAK_HOSTNAME
      value: "https://auth.glythium.io"
    cache:
      enabled: false
    pdb:
      create: false
    metrics: # Grafana has a dependency on Keycloak in this config, so we cannot add the ServiceMonitors using this Helm chart
      enabled: false
    postgresql:
      enabled: true
      auth:
        existingSecret: keycloak-postgres-secret
