---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-post-install
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./common/keycloak/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  - name: kyverno
  - name: sealed-secrets
  interval: 5m
  timeout: 5m
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      version: '21.*'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: keycloak
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    production: true
    proxy: edge
    auth:
      adminUser: admin
      existingSecret: keycloak-secret
      passwordSecretKey: password
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: auth.glythium.io
    # Check this issue if you run into ingress problems: https://github.com/keycloak/keycloak/issues/14666#issuecomment-1272601638
    extraEnvVars:
      - name: KC_HOSTNAME_URL
        value: https://auth.glythium.io
      - name: KC_HOSTNAME_ADMIN_URL
        value: https://auth.glythium.io
    cache:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
      prometheusRule:
        enabled: true
        namespace: monitoring
    postgresql:
      enabled: true
      auth:
        database: bitnami_keycloak
        existingSecret: keycloak-postgres-secret
