---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-agent-token
  namespace: gitlab-agent
spec:
  encryptedData:
    token: AgBO+JOlfpTOIFPcU4vusOTJ8JkxOvEhAOawWBrD5btMmbzfDmdA2un7S6Kc418p3YvMnWGekd6HF3IewttSXA1YezJnSXEb5bXGXvPtSBdMb8fPpNi3tHkD/yo9nU3s2GK1EHOkuRZpxcASK4IzLdjEyushVNygyfd1atw9jJiKKKcMFo3Fvoq/oTL96BmeKaPVTS+yvXCpqQrTTDEJQ8TKEX5r6JziEVw0U6VSpl+Hzw3YrLY7N3os+Gl+8iOv8pI4RBJdqckngpLXzDNj6Zy6uKbWygG5p5J+XcEsbJ+xLJNoEWecIKxGkf6bU9NXIIdtdQUeYFGFi0icJhg2hQZwBZi7QVhyAzErHA2stN4k/IrrXfXREeZgCFsupGBlK7hOMZNjZnQ4As0PAo14nfJyhZh9exrvg//SwDinJ/dT6jRm10U4HOAWju3CNFrQuFNrFhJzwj4l3qeRXXFzMXBW6l+AJNgCq1+tnBv3S9/6xrIhSW6jhcvaKTDjdce8KslbvJewxP5LPeF19rAlfvfsdinEJBuqaaKSj7EOC3cHSr1ZSJWhg2Gx4yL1o4hLgTP0E2ioJpampOjxP4zU2+Iaeg4ZX2HxcNYu6N+h/oGLLWdPoj0KyOWT0Y1JSK1MKXBKPSu5Ft39ETsMBEyVXqyvQZ7LHDeL6K8CBxfQJ2B6tUQvGMOX6H2Yt60W/iYgkWko1LpRt7oTzX4p6CGxSysNb6WzUq+I9pJWk3sNkhZGtVbfPYoDBdSY5e4B/5ycK0PWBzzzWQ8pP7WJ
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-agent-token
      namespace: gitlab-agent
    type: Opaque
