---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-agent-token
  namespace: gitlab-agent
spec:
  encryptedData:
    token: AgCWPu9R9d0xsHbInrKP5T8UH1iG890+OQq/OIm8WoP8vRjL3457K4U6OaFvHIzRBxvPjUbmkwUJQBwob6OZVHLXa8ZMHn8EsbZ3GGoHgPUYUe+UcA0PBQG7KFJSIO0079K9/Nm9i7uW1ovSEFUGMCcG3N4uhxMIFa32NQwncey8LvupiBqG6mdFHFW0hai2/cVAjdBNk1/PQmh/6Zkil91S6/n5CxK91qn9ghc8QquA6YT7hYaTSiRH8Dd5ahI27FemISrfYSbbd+JOwqx1LNwtsFP1a0DhecHm78qGR7uR37jjJ1Xj+Nz6Gv9Ozy0iAFiXsOkj8eS/gmWSm9Y7XKaH1/I3aiSwKywnXhOk6wMd5omQh/pxZfNSAh/0US7nLYPigkGxdRz2LfakzmIuEpwRJiQfapEosWqtVpq8iC1aosIhxrniJX9rlOyvZbVJfl1bdYM1VirvWv8Q+dw6pIB1wSBMcsEjTUST3jIOFDt6zmxoltIjHNq8J1X8OFIgy+Dv49HKhe5ER5ZZ3TQ1c/uHoAxsf3U4drbAJhPz7pGlt3/3EUeI5nWslfobtqSnUK87jZewCCVNcGrKFqt6TVI2PHwduuf5vrTAURQIAxyVHB3MPEFW/ivlkz/plmV8UhdnizlrwKSutR6GjcGKqeKfsZuFm7qnVbJiqL96RZij1dCGMwLa1WwWf/hRw4XBjVc5trzB5izS5XNVjxj8iwTgV0ZJ4UXAlMf/ihr+/XbfFKbLQhMGsqrC3LriE7dr1iKYXP1r57m1rWnX
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-agent-token
      namespace: gitlab-agent
    type: Opaque
