stages:
- test-runner
- yaml-validation

# Test Runner Stage
test-runner:
  stage: test-runner
  tags:
  - pi5
  image: alpine
  script:
  - echo "The runner works!"


# Validate YAML Stage
server-side-validation:
  stage: yaml-validation
  tags:
  - pi5
  image: bitnami/kubectl
  script:
  - for yaml in $(find . -name *.yaml); do
      kubectl apply -f "${yaml}" --dry-run=server;
    done

diff-yaml:
  stage: yaml-validation
  tags:
  - pi5
  image: bitnami/kubectl
  script:
  - for yaml in $(ls -R | grep "\.yaml" | grep -v "template"); do
      kubectl diff -f $(find . -name "${yaml}") || status=$?;
      if [ ! -z $status ] && [ $status -gt 1 ]; then
          exit $status;
      fi;
    done