variables:
  PIPELINE_NAME: "Default Pipeline Image"

stages:
- test-runner
- secret-scanning
- yaml-validation
- ops-and-maint

# Test Runner Stage
test-runner:
  stage: test-runner
  rules:
    - if: $PIPELINE_NAME == "Debug"
      when: always
    - when: never
  tags:
  - pi5
  image: ${HARBOR_HOST}/dockerhub/alpine
  script:
  - echo "The runner works!"


# Secret Scanning Stage
trufflehog-scan:
  stage: secret-scanning
  tags:
  - pi5
  image: ${HARBOR_HOST}/dockerhub/trufflesecurity/trufflehog
  script:
  - trufflehog git file://. --since-commit main --branch ${CI_COMMIT_BRANCH} --fail
  - trufflehog filesystem . --only-verified --fail


# Validate YAML Stage
server-side-validation:
  stage: yaml-validation
  tags:
  - pi5
  image: ${HARBOR_HOST}/custom/kubectl
  script:
  - for folder in "common" "services"; do
      for yaml in $(find ${folder} -name *.yaml); do
        echo "---"
        echo "${yaml}"
        kubectl apply -f "${yaml}" --dry-run=server 2>&1 | grep -i -v "last-applied-config" | grep -i -v "server dry run" || true;
      done
    done
  allow_failure: true

diff-yaml:
  stage: yaml-validation
  tags:
  - pi5
  image: ${HARBOR_HOST}/custom/kubectl
  script:
  - for folder in "common" "services"; do
      for yaml in $(find ${folder} -name *.yaml | grep -v "template"); do
        kubectl diff -f "${yaml}" || true;
      done
    done
  allow_failure: true