stages:
- test-runner
- secret-scanning
- yaml-validation

# Test Runner Stage
test-runner:
  stage: test-runner
  tags:
  - pi5
  image: alpine
  script:
  - echo "The runner works!"


# Secret Scanning Stage
trufflehog-scan:
  stage: secret-scanning
  tags:
  - pi5
  image: trufflesecurity/trufflehog
  script:
  - trufflehog git file://. --since-commit main --branch ${CI_COMMIT_BRANCH} --fail
  - trufflehog filesystem . --only-verified --fail


# Validate YAML Stage
server-side-validation:
  stage: yaml-validation
  tags:
  - pi5
  image: bitnami/kubectl
  script:
  - for yaml in $(find . -name *.yaml); do
      kubectl apply -f "${yaml}" --dry-run=server;
    done

diff-yaml:
  stage: yaml-validation
  tags:
  - pi5
  image: bitnami/kubectl
  script:
  - for yaml in $(ls -R | grep "\.yaml" | grep -v "template"); do
      kubectl diff -f $(find . -name "${yaml}") || status=$?;
      if [ ! -z $status ] && [ $status -gt 1 ]; then
          exit $status;
      fi;
    done