---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: runner-registration
  namespace: github-arc
spec:
  encryptedData:
    github_token: AgCMW1gCMLeGcpveHr2z+qDDHOGWyV8LPi9GyZ8CbdZV/0KB069bl1AWJABOPjpr12RD3UYYKN+W6z1RAIYMU9kc6Ss+0pDJWPQ3IrKn/e5q5fYQv6iiw2ddHhIpCkaRAECRrtqNUwy8hdZBZRAyR3VZI1DpQqfKNOzZm2HPXHNXP68Dv+Mxcczo/a8DVFHHXk6AF+pvoKj0l1T/cbNQSyPJhr8cDAlsICjgo8lboWvjfheovfUmWa1+scx0kZdvQGGS/wUZu72fU3kiAA3U3eBiGiP0oa5wzyUXZH2W768ZGCDtIuIC5/YJ8/SgaYoQljDAH0MQj7/f2lZqSTdtlGSuPij6ZzWVD3ws0AlikhdF2BUoWbsq4e3Qy5CHKKxKL/mH0Qt7fcl7hGUjQGh96cju/ZNTqXYYlkuJ6nkZumEgySVPua6MSPuvlEFKLwl93ZpXuAjs7yGuINofybpfJClPYIok/iP6hi9C5KqU/6JrdbnwQZ8A/79Nd14tXjysNL6tfsd/GTo4OvVlT+IfJFnpsqRO3ciq/3dit/3/Ln/6VdArVwV2YMUxGVyg5jSx/J2CmLNul1ADQJL3KOp6sAmJjLrGJEy+gPtKoMCNYLTD5/3zWoswbxCsw9nLCUaSDw2Re/kRLTpVv7DOeQhT3tXLnm3UImAWQuWEK6mHl4QNdIZELWMy5zwlRpDMLcl2wHwj5PzA+AGKqQRLJOyc2Ew6dixcMmv9oB8iAvORnvjZyBpL3yh1BBm0AgHvOIISGqKdDhCVYcfaHmRgWa5F4b85NSBMdIi/LgvX6hWLEKYWg9RzBvMlyOB4P8mI9EQ=
  template:
    metadata:
      creationTimestamp: null
      name: runner-registration
      namespace: github-arc
    type: Opaque
