---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-post-install
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./common/cert-manager/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack-io
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: jetstack-io
      interval: 1h
  releaseName: cert-manager
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    installCRDs: true
    startupapicheck:
      enabled: false