---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  dependsOn:
  - name: loki
  interval: 5m
  timeout: 5m
  targetNamespace: logging
  chart:
    spec:
      chart: alloy
      version: '0.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: alloy
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    configReloader:
      enabled: false
    alloy:
      configMap:
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "create_namespace_label" {
            targets = discovery.kubernetes.pods.targets
            rule {
              action = "replace"
              source_labels = ["__meta_kubernetes_namespace"]
              target_label = "namespace"
            }
          }

          loki.source.kubernetes "start_loki_pipeline" {
            targets    = discovery.relabel.create_namespace_label.output
            forward_to = [loki.process.set_tenant_id_to_namespace.receiver]
          }

          loki.process "set_tenant_id_to_namespace" {
            forward_to = [loki.write.loki.receiver]
            stage.tenant {
                source = "namespace"
            }
          }

          loki.write "loki" {
            endpoint {
              url = "http://logs.glythium.io:3100/loki/api/v1/push"
            }
          }