FROM alpine

ARG packages

# We'll use root for a bit to set up the container environment
USER root
RUN apk update && apk upgrade --prune --force-refresh
RUN apk add ${packages}
RUN adduser -HD -u 1001 1001

# Switch to the non-privileged user
USER 1001

ENTRYPOINT [ "sh" ]