---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBJtPvn+k65bmzjUD4trwBi7FzWNVpuF0ffXWlf/OpTCno4Sf6rkmmnRSFhXehFCxDCgH1Q3Gf8RFmU65OZGOv7ds9UHeoiqVURv1AiVNzYcl/Tu589pw2G2XPm5DEHoPjvCTGzxpLUTzaiv592C7M/7shGbyC5xn5eREz4eM/xo12OXIrHamJPvR1B3KLbM1OPvrSn5/4CM7n9rt6qPVpxQ4I8o9z/2CwYf5t5fX26M4m2H/OoKKSsNvk/7B0F3PVqoLs/Sg4ysj7CpjFNK7/bzFWAMXpOXXiR8eV8T+GE8tIfB39cJ8NoNeNtQCL1LO0MiWtsHHJTKnATyoh5SgEKVBbsWy5UPPu5j09vbd5pGZn9MEP/fuTLhRMewNW3vUDHW7f2Ay+3ykVkArce7nDOnC89Uo9aw4aw+Raohkib9mhCMHB4hl2IIMLNKWww8MWcAHne6apuAXTl3tn5CJo8XFkKIPuZWGu4VcSnnOmQXEGh3rAq4uZ2Azpv/SxawPrqzXeCpwYEnOwAOpqUBhQ53oqpwXzdPp1ktVMVR7eP8+55ivYosjIJ4B3qmhPWE4Cm9lDIXa4ccuBWXGu+VWZhT9Yz28s12/pYx9wGZVKUFg0HefMxgr5gqj8OHcAVZCNuO4oerIBI9tULcry66QON8I+0r97o+ujBK5tVfjxXYpUsQjOuomYRT7+Pgq0009bZKuC0M1GN
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBpvMAGDZyzJXofp6QT4Jn0ghooz+7J1+jvBsKkIYHN+LF/za2Ay7mVbu9rlFmAPCUZ2W468ca6gwEmKmCz6fm61CJdkRxj0pV8qRy0KgbGRQ9DGJS1dxPOKgCzm+HhZKgNPucBrVA9wt4zJ6Q9KHCpP2gAkwsdKZQIG0V5KqXpOU7VkEEsCc9/nMlxLDbolHz0XkCVQI9Xe9Vvnn7MLIu3pW5t38N5IiBSPZhD0PZvCW3zLh3oDGiFrDT/7bWA9T/nqJ1wnDiBf+g2TGBu+7H76AqGW1resW0urGht+hv8sUbktT2bxh2gX84DseWq9ZAednca8O0eZ+yA+6qDdd3JRZncvI9CZD5FW/9/OuQ/lMGF6MjcSKidgAQ9oLP8fBoP7rKGazZoTZtj6zPL5JDTBhZnF81ripEXjmU8dgJkaSHD7qjHxNYYOMg+Z1TU77QHcMxX2HHLxIhcQsbcKak9ps6+FAVh6deZ5+AyvO4nScxc4zNN0CgPOxCfEI2sCRz+YoczPi+iPxwe+J4Gq5wrIIq6tpl4CmdZc2rLydR+JbBSMaLBcEOGu3hweEtCWWnUzmFSjxuXhEdTA4CafSOVD4tauItNF7bQfappDUrclwF8r3/ZaeN6ie8UHeOnF71kmBhe+RmfAfwahH8B3Awz/w/pqUxBNwNIsPhqjSltA09zWWpBGsfi7qIDcCNNfngps1V160yatD7dBAphXbosZhE0kELsNXhrvxZagZmubg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
