---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgAf78ONRTShDApiJUFfrn0+mmhQNEyx5/gatKkEyxo/4p929hieZ6a9RXejIcwsz3zKm91QhmgQqgLJFv1A9hudjGxyEaODU8pvhkFHdv3kdAwT9vYa577BdsXjkkL/y3sYhNOEX8n0UBtuC0zx7TQVHffOdQ33ycaKJcvYOnh6vtO+0on1Xb13zNWQ/xwz9TQIDLewFQEdWqefnWo6RgAy1JWX9B3pERozL0dvvanoR81EFwq/uZNxqF1hsnSe/OjfmeHo5rCHaaN+GUXqY9nEGb2ctR3DAUOMJ0qAz4WbCZ6JTO16YSozgTj9SN8w7lE5pog0lSY9vrRywXRwTlhctNUSco1E4mxBNEkNRr+Y2vY+GYT3rxq4t/+QKUl7UaPZSrFANASlW1aWD+rxzG7zCAY8U4KsbxHo4m8hud58UXVr6aWr23c2NlaRIWGlSrkXU8gC2ZIM77gX4MOBFc2jwV1POslpTbe2+ekUkD0E8vXdrB84B+nQJCLZ1Mowq7aY/pf+Afp1KeWpTwqgEPQZydcad8WDhjIL53G1fqiAOzUQF94e3Ik+rETHQrOa2iBtEWQAmuHK4vV3zlVph4ZpUyhyGGkZyFDyWVIBD++Jp8nIRJk56d5gLsg+l0jmFfLU3U95Du1q2R3e2z/IZtrvmUFRRoGb4IPAKHFMK6IyzsTgDQAkeMiNE44mrcnQr5pvPjrMqBvj
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgB1TnG5YaqHXC16qcMNGjw0gCUT1ZdWITgYG7AcSZSSUC98GiAUQ/gHawDkV+aJG3b1aI4VsSjcuznFOA82e4d+grqkE29uf6WK3F558qPn5+9AWrENwh+gML4dQfH8qxP409Vpw5mr2ZG/wgGlj0tIl0PxPrftUUPaBvZlXEBJgMy8bBkAZ4CKd1oPbncy1LDRqZgvLn+A9lvFc5277mdAiSS6H7hka58nnJarwDh9QTvmHCiLyfoCsaK9z20+3lAy1BDeNw2f7UWNSmxb1juigtYFdLWhlmf9nY6UwefyH6qq7pgxDKL5NH6Wieh53MnUsaUba2j6MMdLz+TQHadtKBX2CpxmEBQqrVfm5S1blMWnVyMx5E7/aYIj2LdyqDyVm4gKjZnp6FFjmg1foBWGHfaYprPsQ583IalFPRsWvRS/55AEEsNOQlPtEtssqG5Kpt5vIHXW1K0H1Z/U1DkUxuJ080gmmOXvHk/TF7VTIrIvVPL0riW0KSBaX3V6zUxcvZye5+UVRaWMUiZR1uclEAUydxa5M35O7kq4Yy2fjo81J2TXBak9LrNFzdc0dRE+HZ1V+FvDkIvQRKKgRo38B24zLYswhrjvK3uU6H605sP3Yph1aYNkWGeYCuDDcwfbyoA8D3vQuTUDj3GjtF8iHaRht9rKoYkn+kMkm7GZKUhPgwN2wkd3t9cFd3ndjyoTBpLFw+KsYh/boJ8hdej+tVB0cT/dRVtNGTiGdnVV4Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
