---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBj//Z7YfAf1Tmrw3m2qL23LhJlwkP8Ut/m3PBts+xXkvUtg+wB8qo1V3NGZ+YzS8tGcf2C7unZ++kGqv5I9b2sJa8bA4nNKLhGLln3CjuaBFzeynQLEw2Pk/nnKqCuIX+wQxG4JfcjnV7rbTEtnXLelnw/tYbl7/ykgzqB7Y51Dl6889c6nXFlf0zIixj+ZT+PgqgAP7CxATUQIKqwtCa3HDH6ramMl6oGgZEc0RVzmla11SkvSuUm66RGycg8UBzMvgH9kFs9CsseNlH97/6japmVsS3YL946fJQ+H4xQ5Zw+UbPXSJ7zAYRhMNd1oW3gEnUVOp94QdVa+KrUBp4YNAVjHOm2q7hZ6uSqi0rLBu+EAyHD98hVGJrfJ7JUDWWulHJ0IdGURBBa9zRnq/sfpDx8evQPoHnCO+csEWQIhTCdKGwIe0p2Pt2g1ByG/C+bfXVxC4FgoMlEXGrLKH2JXmEK9Sg9DVGKqA1qp7EJUGFtbZI3Yrzt7z3OMOiSp/FVhAPNyvlm/KNIQL17I5dImmppDQ8ITUGMmmCQw8+3AWLcDKlgJpXOO0x+gyeO4vJYy16pFPwA+Ge3xxymYLqfOb11WGqth5uneJBXuq51h9sgoYqxeIF7ZAf2G1fEas4azf1tyHUWmxrWXMTwLBHkb/DdudwZOLnAIaxW4qezEF37PO2Lar1xP1dB7O477hrOJqGX3wngM0xhjPYJRQDHyQpLfU3eifA=
    admin-user: AgByc8y3eJh9y7M+C0T01Pyq2Qh/0WvK9HqcCy6ANkiHWM1fSSQcdKGxcZhL0UsV9nrX39frPQ8dRbU5hKdAC4wpowMAU1JyON9MaEmddW7cfcmXu4PbGGW6Qur/QHJcj6TsmYvFuckEF38A2WTc35FrlIVRuCITLmbw05F8bg4uMDnCWCWM7GVYOwS3Sn4CBl88WesZNSvsyDyJvHgTDob0t6jW5/Hmq9AkaVVC+D8c2bYQGvN+l2fEexTK0F9uvFVRvBKGXSGxHGNXnJcFAf9y/0BM07yYdbOa51wFPuZsEqwvBLCAYuAv3f3QcGH3ywbrNrY0awa8jI823/SjUS39ard9RcgqEDUo+fnTuKYfLA8LTr8hV8Es3SNZtoxxTs2+eI2HfWI/6Fu9PY5UyMvn3KRVy/UCi/t2GUNxBwwTBYmCjOSXdyJ/TKbYerazi7LIl+iLzZTvVgh47vGGywGcyxsMPXM68iPyqAifnpzOJAvZc7DiFve2XQT/D6sDtCAvcY1RRXUaUHD/f2rbp/VZ/XLZ800oMBCauPOBSzKZhYq4RGfDFCoDYrCF0QRdAOcNgEhTNRsi9pZlq78fXDTApIG99Pj8o2/Y5Uxt5YG8mLT/Ylxd89GyQui4v4zreJQlJjBQNHRYp5XYluiqnpkw20J2QrUM+3EcYZTmVK2ESSkwMO8+1zRkQ5+Le4iKmYIagdrHWA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
