---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAixK9suXVqASYcbT0tYU1D6AaL2/Wlr+AKd2u+Qmt0ATWVenR5T8Ut0S7ed9mGvXI5yOVGBCpGF887zPVrJhdPoraYDnkNUms5adjbPp7I2EIKyKQIXRfhoYIVxP88gTcOjDv+kTHHCq/wkuRjlyG+SKdZpQ9Mr8jE3lGGe7i2RkJV/lBE8Q+heyPNu+qya93DEy5CcGDgainmNu/NKJBYTXCAddNgdhjr8EUCv1fbkPnBgTmlRbrPnTqpR9SVwcZUP+NYtDJx2Yu3p6fYv6lemRmwhRN4WYB14XnWDuSx277HwKRcVowVbSVvWBY9zQeE9zdVHZ2+0n3CTHIn2vg7KfEDa05r7rMfH+azxH/OZULTf11Y59QyJ8ReHf1jM1BItvvbx7l1+a+3m4GQh14uuBsc8zDC8LduDAc/zyIxnRK9Kfsw6v3Gf7xzTwTHM5zZExRvh/w1TQ+iBwxQF6tdAYE2veVeLRO1SyN9CG+afNRHxIjOMcBJT3CFrYJq8qHGW38GKByr5bTpWS6O7Fvd6blNmjSKKW1/5cN10Jmt48P5DyURZbqj6tpGCOxnsucTveVhq5DQIf4FdnsL8arQqIqpOCoRua3Qk+kjHiWSfMI8kuzZ/QnOMhnsvyeaatbdc9SjnghnmuaTruBnx9PjXQLG3gF+OZRtGkY0V/JVAI7jYyoG7OFXiWx0T60v8GWFEsWukcKL3hkUNpEBO26NYDqPOCvQV8eg4UWpeDlSdA==
    admin-user: AgCs2wrciK4bP0BHKWbUkoBl8oaIe4nrG8Fp7Ba5rI///qzllk7zh8AS8+54y+QFlq0/HTfz7ZFUeFkmHesJyL41BQxWajre/hpTzEaj/B78Un5HAQ9cf87QeJcDvEBXatuWvWQCiLECdq/VO/OdCV/Qe+zTmIUmJBCJDkKEqmb9gnKadWYohk+v/AqfmWcHKikEx7hp/XMoGQqZJvAf0qFAOUkpJU9Ae+TzHfL5QAnZxd8IAYmfh5k3F7ZjfxhLWl8bghbRbndGJRWGdYJCZWFz160wYveC7riG6o5s+/JRKrevqxN3WomH2ZA9utnk5BQ5pXROsbSMPGSCLQTYymP+C2umhuni8y03Qs6nx6ZLcHTrj/ySz/9pZ0R2l90/HrZBSTN+NgRJoQbHQxoadvSOvn6bkcRTUllDHay8kzpXXkHwFZgpz6FSHyBAcqYbIK44fFGtpdIQleQwyV7eO3E7UNg1e93fvuLanrRZ2tffDHRAIqSWKJ1356IFQ7Rx2Pt8SFT9YeL1eniV119lrtYrXJqc59Or82KSNC/KtSl0Mt89wniJuXwSZmXaH8VaIw2mxNrK95Cmc+Z5ox0b8q+Uj3BygNLuxcinI/2ZcQY/2oxtp8isToq3yFAR5Gd1qZBwhTphFwE5QkqlwveLqvxHyQnCH/WD7pgnke9U/dVvOdXcUZNgxeZNoQ1wyn1L00NozX8JJA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
