---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCcKP9xJjDTpdv+b0ge6Nsl1mfnQ3Jj6TL3fGk5BXCe6yRgxc6sWJhh+5X1d2Fxc3uXe73Ed4IUUkfUuwHaLp9huQHc5fL36Jtu8FIG7ad8JctQ05DnpQrD+v7weBuMQcoYxi4Rp2eh6YfenPlcr3DoNboMgt/cEt+S/BQWJTqe3pUuHCgaCKL4De8TMUQhkIt27ywheADJt6AZu6ubCwdRmewoen4oSSqeeDBbCBw6E8qxS5ThyyQMVLYLUXcgLOt8tlXDLrSO0aRis2rQs1wDMADcGF26yjVAE5t58OQIl1hQITXNwhciPLhZsYh7VbW3/JZneHhGw9XM/6gf/BhpQ/6cMbS12vNgvO5zM94vC75LHsYpxuEO/KjEUZRfbvr/9dzT2zAGTMDxGElK5pRYxkaeZPxOD7rIsSIbsQI+HcueBaYeNTEDCkvHLeLxyMd2cB0a31fh+bls63PB2fTHshIvtQsZIk2Pi/qa+8ONHSoVY8UBphh3lmXPRcUkzZgk6+50SCPLundJu2qBilIpFtSYchik9qyAUB76zdmtt6+vQquMvdgiaEOabZAQixcu4xvvXpgbQf+AcDIXjyql03qM7ks9SNnqlUf99kbfoXBg/8Pe+LC7NhrroYMceXXTXTI8mrcyy0Lc0CV5M4X5lIj54HiAeObsKk/ZAdKgUzpIXGgtqOD1fk97IBx3eMVX6BmYvsZFDZHoBp0KjnmKB9F4ZcPuU8s=
    admin-user: AgActdwqqbkK0R3iIE+nI15KEqUpyeghMpAqff267dqsGyZbggl2DDKBNwDNzov8qlxCpmjFn5LJIz/SSuzxoh82uWEJ8/LQAFHIP82Dfl/AAdWIo6OPtvdcOFhEM0bECR6BxYbUA76bEZV0eq7dypZ3GkGjl8vellsVDbB7Q/5jZwqR8NJ7JRfamLOhh0vyCe1HlqLFQBeVWKDuVx+fQLrj+DWZsBMbq3RqgXhSB5L7dVURJYkfJ+7+crMuZRINc4cg9DtghE1A6Cwfr7fRdG5AGjQZ+vPDgjqCOpzrKcThG0skjuvT67jqZ/dxVltY5GPoQQTLYh7pqfABWT7KFoNw0gKLQWx7GwhMj+1E4EBIQr+dh5/P9HeASu56ta0q5qS3W4Y+kZ/TtV3A42F0HT2scOKIhuDrbxY/0nuzv32pB/pV5JtR7GH8RFoockoKp8J/cQMbY1kFLFjfII/z9IusAnRjbLfwZRlalpUNd4h2dqE6Ga59tb0A2X+MZ18/RMxFq5/plX51fuypnvYnEiHp7teg1TYtx6ucyfez6JNXLMHPmqpq3tBeAbXtnBauIHHeyi2T6g6Ldj2BukHmiEgoPbwydjURSnnhnzXLWP5LtkPyIlrbEMt8LzuiM8/fdGsoPDh88c/9lFFQBzJRpEzu2m0ykoWE1P+c0VSxdSvT7d+QFp7ui5x4b3rY4qm+fXEMsqHaVw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
