---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-cni
  - name: istiod
  interval: 1h
  timeout: 5m
  targetNamespace: istio-ingress
  chart:
    spec:
      chart: gateway
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h
  releaseName: gateway
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    labels:
      function: ingress-gateway
