---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-post-install
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./common/istio/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  releaseName: base
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: disabled
