---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-base
  interval: 5m
  timeout: 5m
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h
  releaseName: istiod
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: disabled