---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h
  releaseName: base
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: disabled
