---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-token
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-token: AgAW6YgpMLieXmNYr1qPoG7rYEnwnAYY0Q8YsyU+HzLba8xqCX5EDzv/LtwDoPBiEm8C/van914nFZQaEnKPvecKjNEFvZiW6gTV8X85kFzRJydvp8OrFYZ+ybPFNp7MTah9X+cSMusxME1dPzUz1yMxVUJwO7CgGZIzSfphy626sGHYZ3XzItGzH0W7ZIRCXoxriguN4htQXlqOwgp3+ayyKae5csBClbl9Ph9NYxN4BjDiuG6pM6n+5JHp98n8DDGaIRqCrtpZwTK9HSM3D1ZqWcIqKJHTTxGedI++B2iWs44ptmBSjCKv+P01kMWsNwlk6ZgLqDbPF/r4E5yh17qKHzBFEQsUDn8Zrw+jQy355F2xtQSTfKz8EL/iGajua/Pr+r9ldvY/Bw1nFoSkLhYJSSN47apI8nctKuDdpJt54BV052GnJI3qay3hRau5EKvW7lCYF9WfeW7tNem4zEE6PDIzjBX1WXVGxh8YAdqMNHoL1G16fm5dmFfrjLQAi7o21QN46DwBn1w1Iu7Jg4CcnjxGadWsaTM5CULwHGzPt/HqdtAV+1BClRrQxvXnSiM0POV2BqWGeYLjix3BMPcFEeoC74ns4dbLPBWhvJ+3yOeSBOVV2rImkrfzsDfemR37pSSQXS4S7EpXB9VEh33b9Mor0LrzKlWRf40QUfVs6Z2nRTXMQzL0D/izVCcVQ2+odBBLtxHzTAlYvwl7wm0rZeHmch8M9Cer
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-token
      namespace: gitlab-runner
    type: Opaque
