# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: harbor
#   namespace: flux-system
# spec:
#   force: false
#   interval: 1h
#   path: ./services/harbor
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: initial-git-source
#   timeout: 5m
#   suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-post-install
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/harbor/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  dependsOn:
  - name: keycloak
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: '26.*'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1h
  releaseName: harbor
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    service:
      type: ClusterIP
    exposureType: ingress
    externalURL: https://harbor.glythium.io
    ingress:
      core:
        hostname: harbor.glythium.io
    core:
      existingSecret: harbor-core-secret
      existingEnvVarsSecret: harbor-envvars
      podLabels:
        sidecar.istio.io/inject: "true"
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 256Mi
    jobservice:
      redisNamespace: harbor
      existingSecret: harbor-core-secret
      existingEnvVarsSecret: harbor-envvars
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 256Mi
    portal:
      podLabels:
        sidecar.istio.io/inject: "true"
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 256Mi
    registry:
      existingSecret: harbor-envvars
      # Hardcode the username here, the registry Pod seems to disregard the envvars Secret
      credentials:
        username: registryUser
      # Fixes an issue when pushing images to Harbor
      relativeurls: true
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 256Mi
    postgresql:
      auth:
        existingSecret: harbor-envvars
      primary:
        # Just reducing the number here because I don't expect to have that many connections
        extendedConfiguration: |
          max_connections = 256
    redis:
      # The default bitnami image does not work on arm64 due to a jemalloc error
      image:
        repository: redis
        tag: 7-bookworm
    trivy:
      existingEnvVarsSecret: harbor-envvars
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 256Mi
    metrics:
      enabled: true