---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./services/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-post-install
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./services/harbor/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  - name: sealed-secrets
  interval: 5m
  timeout: 5m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: '20.*'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: harbor
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    externalURL: https://harbor.glythium.io
    exposureType: ingress
    service:
      type: ClusterIP
    ingress:
      core:
        ingressClassName: "traefik"
        hostname: harbor.glythium.io
        tls: true
    # TODO: Install Jaeger
    # tracing:
    #   enabled: false
    #   namespace: harbor
    #   jaeger:
    #     enabled: false
    #     endpoint: ""
    #     username: ""
    #     password: ""
    core:
      existingSecret: harbor-core-secret
      existingEnvVarsSecret: harbor-envvars
    jobservice:
      redisNamespace: harbor
      existingSecret: harbor-core-secret
    registry:
      existingSecret: harbor-registry
    postgresql:
      auth:
        existingSecret: harbor-postgres-secret
      primary:
        # Just reducing the number here because I don't expect to have that many connections
        extendedConfiguration: |
          max_connections = 256
    redis:
      # The default bitnami image does not work on arm64 due to a jemalloc error
      image:
        repository: redis
        tag: 7.2-bookworm


    