---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgCHT6gFefU7P6fg7GeWQ742dVlE233nsMzP55dBJTpGjc83DB7HbvfSzdo9re92EIF6e0Noh3uG81kLvCPw5W8Reso49EjuxTak0ZyBcHTkiUd+VjZGGoodWA2vGI1tIxciPFMLbkAju39djtQcpoV/8O/ZdGmZ4KFx6bwDDOx9XtGNzUBETcOC6piKiEyzcb/Qel9850rZ/q1o39mAeO5wIkYar4ebuAxi9zny51Hq3V6HYuKkjk3vkTnF9CXUOl7w8owGnQZId+St4ubpsp1CcVj2Hd2xPZ6ZiAIvMebImvm4AxmUJamSIt+L1smGkMVkMyyKldvoyJhnYqIYh/yzc6x1QAY85+ZUP6nSeIZDgLJunKEVW0w0w3tbwm5Zekx+QslAHXFQmjIxKHVKjwqqwKZi90RfcJ9FwJIY3g47W4C4qrTOxyde1i6aNS2ScrIfgx1avQI6lIRdIFGDZP6IN540gB4YV0ionxpA9AVPhJ3Lh/ebG0e4HrF6cG0IlfjvcYI6RwN1RFv9AqoM/H9/an0lpgUdwgV6YjTm4WOE74fG4l77HwaSA+N5PHrzL4rFQlHF6/gkFkbuoqmoAWKMSmNg3poq7Z6yCyX7OKd9nRa5Cj7Opaoj40jtuQiDdUWZMApxtdaevvQhykvETuTFWAu8cYyf1I/KUxBEVcGhRfO3qJvKHnfIog9VzrN8pdddWIJdg3vz0HolV7O8KzTYnGekBjgElXw0Mlud/JmeTQ==
    secretKey: AgBtNl7f3hvxhu11NJ/B9L+8bvVolEJqMVuCIl9kFHQvnjsmSzkmbFCgKaxmmZQZQo/ily60Ie4vsudiYpONn92H3uVL+BpreUuz1LQeVURSnara1+qERkDYbdVhMEAiYW6xhufUN5nW9iap+Cypvnk4bj7u2a5fNRR93+1Jgs66zxwgzPHp/QmRsE1NR+4ffZBDadURf7mx+RYRwub8Atkv6Oy86qXdOKDC+ej7pmX2YnRvTAWwpRXVjXKa4LuqbO+slWNBVfOpuFp2Z9GlOmxiPablnmajgeU+9NmKdmuICJO8hrhRsdv+f6XgyIS4u+x3aIZwGt8n/GeBpi2ilcMm/Zce8zqn0dyR9iLlfmO8mzCcWQbpYFG8hQHJIYkGH2f+HnVB/8B2uUwdRxbGauZfll9xypjsenjj9wriAyco5kUsYxn9Sb5m1o6ZVFqFJAZrYegm9yPgbEccPGswwl0fdQVvQcbBO+pjmCn8QgNYet3fUy4SiNv1T0MDywzh5GRUsLNATtQad7SMAEuzBPWh4GyndsiLS0mAB4R3lWZy/hGi3m68ppHsuQb2GUP6lB9DiKuACvyc7SKDzUyQok+g3XvWCKwRmjDIBdJucAmpnNSDTm2tm0/co5ScrrupxbVn2W/CBNH74GKD6Wjc2UosGGXmqiXVXVXqNXxa29oiuwoh1+nPADYcQcF6rUd010YSjlLD7QZVpUunrlJCPDOebrNfO4wLYs1E2+3OMiMGWw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
