---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
  suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-post-install
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/harbor/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  dependsOn:
  - name: keycloak
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: '1.18.*'
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 1h
  releaseName: harbor
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    expose:
      tls:
        enabled: false
      ingress:
        hosts:
          core: harbor.glythium.io
    externalURL: https://harbor.glythium.io
    existingSecretAdminPassword: harbor-envvars
    # If using existingSecretSecretKey, the key must be secretKey
    existingSecretSecretKey: harbor-core-secret
    # harborAdminPassword: ""
    # secretKey: ""
    portal:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-portal
    core:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-core
      existingSecret: harbor-core-secret
      podLabels:
        sidecar.istio.io/inject: "true"
    jobservice:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-jobservice
      existingSecret: harbor-envvars
    registry:
      registry:
        image:
          repository:  ghcr.io/octohelm/harbor/registry-photon
      controller:
        image:
          repository:  ghcr.io/octohelm/harbor/harbor-registryctl
      existingSecret: harbor-envvars
      credentials:
        username: registryUser
        existingSecret: harbor-envvars
      relativeurls: true
      podLabels:
        sidecar.istio.io/inject: "true"
    trivy:
      image:
        repository: ghcr.io/octohelm/harbor/trivy-adapter-photon
    database:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-db
    redis:
      type: external
      external:
        addr: redis.redis.svc.cluster.local:6379
        existingSecret: harbor-envvars
    exporter:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-exporter
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    # trace:
    #   enabled: false
      # attributes:
      #   application: harbor
      # jaeger:
        # # jaeger supports two modes:
        # #   collector mode(uncomment endpoint and uncomment username, password if needed)
        # #   agent mode(uncomment agent_host and agent_port)
        # endpoint: http://jaeger.tracing:14268/api/traces
        # agent_host: hostname
        # agent_port: 6831