---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
  suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-post-install
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/harbor/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  dependsOn:
  - name: keycloak
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: harbor
  chart:
    spec:
      chart: harbor
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 1h
  releaseName: harbor
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    expose:
      type: clusterIP
      tls:
        enabled: false
    externalURL: https://harbor.glythium.io
    existingSecretAdminPassword: harbor-envvars
    # If using existingSecretSecretKey, the key must be secretKey
    existingSecretSecretKey: harbor-core-secret
    # harborAdminPassword: ""
    # secretKey: ""
    core:
      existingSecret: harbor-core-secret
    jobservice:
      existingSecret: harbor-envvars
    registry:
      existingSecret: harbor-core-envvars
      credentials:
        username: registryUser
        existingSecret: harbor-core-envvars
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    # trace:
    #   enabled: false
      # attributes:
      #   application: harbor
      # jaeger:
        # # jaeger supports two modes:
        # #   collector mode(uncomment endpoint and uncomment username, password if needed)
        # #   agent mode(uncomment agent_host and agent_port)
        # endpoint: http://jaeger.tracing:14268/api/traces
        # agent_host: hostname
        # agent_port: 6831