---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTPASSWD: AgC1NAJG1bGaXiBM6cLkanlSf2zmsUbjwSpdf9R6JTQsqmbn9FGP2apZD8W3dx6FJUlFxyPidoUez+CGTsnzHg0BbvqqI9HfxYnKhcVqLnRWJ8sEVj11cUIV0/uRY8UgLQ8gCH9ixAEnwk82n6U8z5n+6DVaiyUadL8AxZWH3Za3kk+8gZO5CqAuzR59hU8chQeCbvLgWHNAGswJB61Yz0045ZHZp46Tiu/yEGsUI92yrnT5dmmc6r3GAr7KE01mzqaQuqtuQJhOW8KqSnsCAmoNOsg+2Kqg5V4Rt0xHW4DwJNeguygrNrXmU5lLvdNpcRxwYI/TJ2D6tXkJoEJMpIFcq6uUQgXm+li1Mol8du7GK+fJiLrm2J2AJLt3jMI0dh5jONVN+MTy6+j8Kds1t2Be7HJxKShGVryEErMqPoUntATIija+a9MicWbky1zicieVYtBqZOGARCltI0/lKsfPyNw+4HgKsHbq0qv8DOdZUwZNOKunBPl3viwk4KrCkbel1i2pf6IVIYJjg3brG0ieGtyWTw1xjq4kSFP+P9XDaxJRJfqSm6ipoVDqL1npFR6s1eLQBvgBm10FHOAZnBYOJp0vs6TA1TUKaw13nBaYYDDkX/PiYUs6s/+34+oNMOI2X+jgZFnxSWARhn+qlQlNbTR2YF8ug/xBKMNlzbYX35W9NNzMJ4kb91U0TMPBw9yCIuWyWIN/eDioEWWiktgShvJONa77i//kVvYaFGt81vj/FdqpyL49v1wGvR0I5CP6hQql0dxUOBTX4xpD9ImBcmoHhvIFflA=
    REGISTRY_HTTP_SECRET: AgC/xaEKZtQxC+XAV4F03u9+lOPBka8+AcJ9vuxg5EMiH0D+F8htO+4sTW1TmI92qxDsiZ5Ak9u2ptm2fL5Ym18W0y/VnNyPuu1u7bxespwzhY+9g/+a9V3sVBghf5y5q113N9McnEdJRh9m6JVLPOMgQa/NaMQdEtDTu5tPvEmtI3tv1goYVvL8LeoI6deEohOsaAyDQ7D5hgkWlI43ikhBZvEz4r1hrHXasnKyMJqDCgay86B8Lsp7ilfrANlFjLPV9yWGjtDOoGLTayILbS5KKfWc2V6/SKeeKdrvSw9N32NjNoftX1ISSbp6muZEcbeRV2QkYjZaPkQ+ZDjg9LIVFUPwRjZ9YKt9ns4JRD3+8nbLKeiwxA0WAusoK6hEGPZHGuEFMrVCh3bq6r0SYnvaNt8x9xyHG/wvOSJDo2q4vySonBG967QQLt6IaV50/k76ML4If0TkjC/NJuqKg3abPzseJbVeFvZ4aW5RGRfTU4beQhba6Tg3D9LQ+u/16D0WVcC2IcgdC82dqcJkSLDS3RDhOFl+9DvR1dmQlHgnaRTnRbGsnLU3KDbZ61iC1sjwYl2K90tzG5f8r9wgfKuY5cXf84sE0xYU8tjuXV40fl1N73MnPCQWj98Xmx/S5Ib5M+Pi4vwNT0/65xO02AMJ8PAAsJg8mD2ADNuRcFwiAmwjwkdw4bmHUxXD77uhparIxvZ4YVDiky//ELp/f3vPgZmghTyqrBYEE4c0o1sYTA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry
      namespace: harbor
