---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgAuswAppH65xgyOAtkTtlsSVa9jEf6s1oLmn66mDXfQbxdurt7ioN83+rtTlXBQqNBrRX6Iv+H3PRZ2dJV/MiWND6nMViK3MdFHINjESbKtDmi9i2GSaub5mqxJW9P2IDpLP3gEJhprSre/2CYYvKw7+pJG1NJQ6LbaGIkl2iWTz7Ljabgzi53PmiU/wnCtdTB8UviSxAxEreF14DO31qBeSvGwxwT2DMYqO9s52JxpVu2MCavdVroCxE/uaVmqAF8HE/4DuZvEibS8vQYYATGhD0EX2r61So+uQFHi/IMVT6zorihI0U2OiWI++ckbo/AFpnl5LWyaxlDkbJsiRxLJnly4X4sFPAILr+9dF3oIu5EZr8UDd3qCNw3Wu0Hnhme26eJR6r3T4bv7BABt55BLCYrHuRtOwgvQ0IBL5mK/Qn72MeiT5K1Oingd9qw7rt2RsCp389FrOVmOGR6eOoNxNFY1ojBQOn3MoZlCqsL6/ulCxKolhIJ3Z1lx+hrvoXRIh+0mxsbf/FQaGUWhwUCzlyKhOHwb5rhN+h/Whec4M3EE6QBVrWgBIrgq4NAqxa+DuPwLQB3Y5Icbu9Vo8t8ZF02MX+fYaG68EVj9A9KlPKhFsSxA/SoStmOPEwxGwyYQDvBPx8mep98EE2g9v+IBWMqzTs/UmPlj9l5ZrG/x1AgTFVWJU9IWZhZayKGa47pcO1BhJo5t2ipTkav4L112GrNtsqcMnlu/Sml6DqYj/w==
    secretKey: AgAamIjm6HY8DI+DsUq0/MWuvT5Tb6M1auol9s8O6yod7A2qRCRLbGjgXZtBcyKZucidbHltGjllZ5sNXGfT8ak+zAa17tud0PcfG5zOkjEp9S0WU30SofgHmYaTwGT4TLzeYOtXUZ/z/xtYMS5MuIh4RGfZXktL8xxwOkju1Py4BHkry92oE3NCtxJblspZ/neFgWhwlKUEWjU4j8J7Bz4yvh10G6T3SMleq4ZBw+FJhT2BKKhN6MPjQaaiKWc1Te4sVttoxN0rdC3PvV7B9GtcqAiJKbhm/rXbgMXePVXezrAGCBTI6Yc17Cem2UOOtBOUNzlq2XqwDSvJiL79QH0u7dum6Io1KIeSYOV/OPhL0cCF3Y4nrT6O/tiRXCjjf/F86kZhUBUen+ec8cO0Li9Bcd7J6iVr7OLI1PKkPgFhRxmvu4q9DrKXCPGD1LOMlPD70xR2tsxyNm/n0WRYhP9VZ7KsM3QjANq2EI2RTPbkqiE7os7XJ1mpG61wAjDPW+2fczZ++JQLlEwiKpNm2w7FQd/e4/YAftlLdVFwNhloOfKK/q5tJiwkgVH4ue4O5Y6h47MKXARYOEuXkt3o6pN3n9aRPnm9TN6YG/R3SRlQCxgKNn3wUrbPVhxrVbIcbYshB7RyzwYw13aLsSePwrlIsnAKv9P0IHXIBhTxtfd3Hu8QywImZvOmnGNiRLml05qaEPRgwy1tPBSiQBEZj7quyJJXyIc/s7pBNu27tChs+g==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
