---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./services/portainer
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  targetNamespace: flux-system
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 1h
  url: https://portainer.github.io/k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: portainer
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  - name: sealed-secrets
  # - name: vault
  interval: 5m
  timeout: 5m
  targetNamespace: portainer
  chart:
    spec:
      chart: portainer
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: portainer
      interval: 5m
  releaseName: portainer
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hosts:
      - host: portainer.glythium.io
        paths:
        - path: "/"
    