---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  - name: keycloak
  - name: kyverno
  - name: sealed-secrets
  interval: 1m
  timeout: 5m
  targetNamespace: monitoring
  chart:
    spec:
      chart: grafana
      version: '9.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: grafana
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    podLabels:
      sidecar.istio.io/inject: "true"
    envFromSecret: grafana-ini
    admin:
      existingSecret: "grafana-admin"
      userKey: admin-user
      passwordKey: admin-password
    datasources:
      datasources.yaml:
        apiVersion: 1
        prune: false
        datasources:
        - name: Alertmanager
          uid: alertmanager
          type: alertmanager
          url: http://prometheus-alertmanager:9093
          access: proxy
          jsonData:
            handleGrafanaManagedAlerts: false
            implementation: prometheus
        - name: Loki
          uid: loki
          type: loki
          url: http://logs.glythium.com:3100
          access: proxy
          jsonData:
            httpHeaderName1: 'X-Scope-OrgID'
          secureJsonData:
            httpHeaderValue1: 'admin'
        - name: Prometheus
          uid: prometheus
          type: prometheus
          url: http://prometheus-server:80
          access: proxy
          isDefault: true
          jsonData:
            httpMethod: POST
            timeInterval: 30s
        - name: Tempo
          type: tempo
          uid: tempo
          url: http://tempo:3100
          access: proxy
          basicAuth: false
          jsonData:
            tracesToLogsV2:
              # Field with an internal link pointing to a logs data source in Grafana.
              # datasourceUid value must match the uid value of the logs data source.
              datasourceUid: 'loki'
              spanStartTimeShift: '-1h'
              spanEndTimeShift: '1h'
              tags: ['job', 'instance', 'pod', 'namespace']
              filterByTraceID: false
              filterBySpanID: false
              customQuery: true
              query: 'method="$${__span.tags.method}"'
            tracesToMetrics:
              datasourceUid: 'prometheus'
              spanStartTimeShift: '-1h'
              spanEndTimeShift: '1h'
              tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
              queries:
                - name: 'Sample query'
                  query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
            serviceMap:
              datasourceUid: 'prometheus'
            nodeGraph:
              enabled: true
            search:
              hide: false
            traceQuery:
              timeShiftEnabled: true
              spanStartTimeShift: '-1h'
              spanEndTimeShift: '1h'
            spanBar:
              type: 'Tag'
              tag: 'http.path'
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
    grafana.ini:
      server:
        root_url: https://metrics.glythium.io
      auth.generic_oauth:
        enabled: true
        name: Keycloak
        allow_sign_up: true
        scopes: openid email profile offline_access
        email_attribute_path: email
        login_attribute_path: username
        name_attribute_path: full_name
        auth_url: https://auth.glythium.io/realms/master/protocol/openid-connect/auth
        token_url: https://auth.glythium.io/realms/master/protocol/openid-connect/token
        api_url: https://auth.glythium.io/realms/master/protocol/openid-connect/userinfo
        role_attribute_strict: true
        role_attribute_path: contains(resource_access.grafana.roles[*], 'admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'editor') && 'Editor' || 'Viewer'
    dashboards:
      default:
        istio-control-plane:
          gnetId: 7645
          revision: 258
          datasource: prometheus
        kubernetes-nodes:
          gnetId: 8171
          revision: 1
          datasource: prometheus
        kyverno:
          gnetId: 15987
          revision: 2
          datasource: prometheus
        log-viewer:
          gnetId: 13639
          revision: 2
          datasource: loki
        opentelemetry-for-http-services:
          gnetId: 21587
          revision: 1
          datasource: prometheus