---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  interval: 1h
  timeout: 5m
  targetNamespace: logging
  chart:
    spec:
      chart: loki
      version: '6.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: loki
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: true
      commonConfig:
        replication_factor: 1
      useTestSchema: true
      podLabels:
        sidecar.istio.io/inject: "true"
      storage:
        type: filesystem
    test:
      enabled: false
    lokiCanary:
      enabled: false
    gateway:
      enabled: false
    singleBinary:
      replicas: 1
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
    resultsCache:
      enabled: false
    chunksCache:
      enabled: false
    sidecar:
      rules:
        enabled: false