---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack-setup
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./common/monitoring-stack/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m