---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  dependsOn:
  - name: prometheus
  interval: 1h
  timeout: 5m
  targetNamespace: monitoring
  chart:
    spec:
      chart: tempo
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1h
  releaseName: tempo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    tempo:
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://prometheus-prometheus-pushgateway:9091/api/v1/write"