---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgCEpPwDfDwG6R1er3PH2cauYmVDSribmQTL2y968A+Wy856zP0yj5oIDWUF5tccR6N22TWsMC5cJI5sfW+5gkEorUy1iIu8reOXMp1W4BwZ3+kzAHMw+p9HgqME7PUqv0Ga+Jg499/SVub4V/g0D2TSfmRFpSu024HMIRp3dOrtoG7/bWtA73l7GugjxUsG9RWBAxmcpM767d6I8/TJreHzyf2Ectkx5z5TPuTRFaKZ2m6m5vkomMo8mq+NvYUn1n5UsmrzwkkS/fyK9/MIka1PrPb7zgKisJFs/Ofpng9X7Kg/Qn0nzHWnIM7wFEakhVfpxdWjPQpWYelqNF03hDGcqdAAk5aJI7NaXWKsTOvjka68PuJ4qbtAN+Oj9q//wihA26u3l0ppuz/5QmmZoijPKPDW4b8qnIyKXD1fONJ1/znR/a79StiP1FHH8AUO3e8tqTFWKNeMPLVv/NXavJuxOQveA/k1I0k+R5G6QHM4oFGZnS/gBt/qalELM0iIgvEul1mk9i5Wu+Zhj1xu20t0vvqQjtGuWJa/m0Q/kFchMiu0lcDVj+XZL7v44tUPKKxDUpYoozczkPGyeht1HUtWVw28hxKFFsiondMQicr464p57+sxiwbcok9cmi/0EAvXKGa/sQbQhcUdsxevN6D3i/g0fvVBiFm4ffPmuDcJqpiNKJ/dBFAmIRDxpWbujTzHUyO4zaA4
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBOu4dBfEDTG17I6xgU5UMcQtGegODxeQGJ7mv1yNgBMQC0UYb5Z2j0MgbNErI3QewNewU5UA3j0s9sYhgGVj5xGYYWjpLxlmwV8XzX9sQ/bbzGSuyCfcP6GXuNJj+uVNV4mdcJF+XpXjDe+ls+mAbJpR440RpMmPIdc211FXlffRRvIGJWZVrBM2mxdcFKHj5ov+u0mW+T7oK3lqNEVFC1R16Y/1erwzZmUMdCYUlXkKjxlIJpQ6k1xObKBd7cUY7W8weQqoDvBou6sV8BEAr/Pqdqjdy3Zf5BeRhACL87Dilj9/evCIca9r09BKcQndrfo9O16NPd53W+xWDi46JSuf0fUAqAEfn4UptKdT01NQMb87GTYR/smcx/ydyQ+AI3TfZs8yB8gIf3DhTDZYqy+GGAP5oee/i7Zjn47ve5UY0JrMSPNa/HMPEBbgqmSsbbk4829pzZFgYisXEc5/Q+bRhxHCwRXfrxy/7TqF/PV7QAw+sEyMOfK/aEj7IFaB6krkGUrOJhXKfntCFV0ZbTQrXH51pbQsW8QrmcBYcJMnYwjhphN38moK3ivKqC3fHWDvkyI8IZhJiPzpIa8E/iiLUr/BR6WY0NoNmjgHWe1ztme22B5iZogeQlc9mFc/4MVJWYuHlgbEIQo5IUAeDPB93rWxyU9h3R0YXhwF06ZB8UU1MXzFnzKdeCO4tDb5GE3rNVRvEPBod+OuUdYBFz8ZKtJzpr2FWt9gdxgTLAXQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
