---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBfwtyeOBwbAYksVOEeaLRchW/ZFsUzTmGV5qHEFUaMDgqoi9HBrYPxiVGgScJEiLhSL+EfGnfella8XVuUPJWHgR3VrjinGnkBsEll9if4dOS/77FhaIrDCTaTfYovd7Svs/jbQF93R2Y7JFihpkdchQCRdUfMbuz4FqfHrIU4UOYjz2guRCy3YkxhlAyr0aLNWnxiev9kiqRTYq+mBu7GCWlzbBp2T1tCY985ohm4jOfc8RTg3dTG35hNpQ3rEJzkmQbIEAAgYjQ6T8R5JgahjhaD6Q6RgJWQrbvtDu8/oX0igP/FfxhEc3kBewDm2D0W+ith7HSiM+5F3xVoB//GEoie2BNwEAdLypPQCZLL379/lUsUHSIvS2okRN1qQ60v7FIyiS65LvB+WNhiM/DBDi3bgaCxWMDWGlJsEk1lor3Lspv6ebkNKyDweUbpvZUqjE9dxQ0aLkhx83n98I25UctQWwRPZZ312gHkMHCpqodUCugwug0huVjuADMYeVoE2MRgd1ko40Xmu2s3G8MnCqmLXJQsHhl32KiYDML38BI/eX7P58nFGAogI/hjOoChWUR+acbB71ZIj+pe0CYmTPl63AKB8DaATdCnpKJudGvF2wzRn7x9vKmHs1Hp6ZmMXrqljspoS9VIXCM4gMK2oOoC4O3C0l7j9bFegnkdPp+KPmJYKoDe2lQZdhB5m82ZDaAPKmjV0Z6CYbXbpsVNddsuFedFeUg=
    admin-user: AgAVbyjH4XITLqZ9Fl6cEHCOdNWeQY6vSH+R/iAi2C51RnOwvabR4IIOm+EqP4BUnKxXUsGyL3muP7vCrHEmUE9K7P9Tx05mAzrgXc2FOfIIgKwP4hhK9u+ZeyDG0H7YsEUxu4tH1sLfk8IYOzHPfOSMnQw6zG8RwL13Mfgn3lgOfwJ5hyB52VQQiT4R/wwv/hMe7PsNH939YuZgPPR+OCxXW8F+Kz9oFzo7f1omdB43yUncqlWmOk+guW/BGvPHCyt960Hn4Yb/dVm6G4IlHbNgFsF5GIu/2hff42kBFJrGqkjzC9ZBvfHN4bkjLBw19iBNVglhssYH4sViBgrxmEwC2KtSrbSFdT5NengEeTgghnxbDjYPkMu4iZGo3OuZ4S72Y5K4nj2Lfb2NRp1n8RAxx8Z5f6Lx9sRbZ6JszC+1SRvg59v5qMQN0UwlQGamKY8Vnz2ijl6wncKpPM1yrhL+YzZF8UlWSxDZTWIc4h1voBBhxUxHwSiI8nKu+BF3RT+a1hc+h6EmzSIIcXjb4mdvRW9hw5JU55kI0HC9uIBus3+/q3uxLuNPF0wsvunZuMeNcWHSuMeEKngOCnh3D1Pi7oe15wKYaVZ59LVKnNoDxODooWo2mCkcjUqN/87N8HPB46cGLq4UrEWmI8RwzBrNPMl6GCxYQgqxZ6AnFe0Z9RMuoz0SqI9hdfIDj84YypSRD3/r6g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
