apiVersion: v1
kind: Secret
metadata:
  name: grafana-ini
  namespace: monitoring
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: <CLIENT_ID>
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: <CLIENT_SECRET>