---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgAp5K6EZMS08vKMw5oFFJzjfUoybXpmIrSiF0mcvlMQjj1EvCbKN7W0kZlVDu6d/8c5KbJHcKO/XaGwgMlYGhkiVk2LGbwSmQUlYF4B95+Mbtl9WgZRVJd2Amax9q82ckSam8Dyr3sw9qox6ONB483Cn4UaFGWJu1xDQb/CKUwTRR8tfQDo9vuUm+iFjwLL9ExBBk80tfo/3xPp4pSUxM8vw260DQ2hVwon9KW5XbbN6rHP3QXjl5gGiPa9txPURMp9ZyArKDPmGMdRQn9tjwp5guL7O5Ij1oJ259mIDHQXesLHwADhcFpc+JfSS2OUg9to3vnZbFQWdPI7ExsqN4ig2YFoeghzD0X+AAQvbx6Lnsv19liMu2QHLWacPHx0rIAtIyELHtRZgx/N1fkVhge0QVBSS4PCR3frjgi5G1my/VEdk/x2iOQkGX7SuGHjZuuzBfz3uqw9XA/gGHxqWLfa+dE/Wsi3QTuROum+VkobOY7VU0UYPFH7M7xO4yFSa0hy9znCnwl2CJH5RTQfIW6znvyGBPEQXSmTaYOGwSjiUw2lPB6IkQdqd10j0uYN70GZC/CqfMWT2TZ6RklQDlYhZhkJ2lfIyv+FTYOMQ2rn6Lp1pdQw73ZnnX9sCu91QLLgDK/MVTyntbOkTjPBKmK9fdr8jY7BBseuNm+xcI2KVm0ib+MM5jdL0+rbK9o3DYGvvsBGUnWZr1j6Km+4
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAPfX4Y3Q3kMT2t5c7aZNmhOKRB45jGw92ZYIGAUBL5fjvVyi4x1Hzbot0ec0jth7+WpkcVqvS4u4PFGHdRbpU4LXQM7ftyHaCegmicjppWEim2j6f8m1zmGY/QOjGF/SvsuKC5c32y0l22l/m5deIUHWvfAv2uOnQeEg/EvSHNzVkv5dYTgeoq6ZdM9WvchQABA8aK80hPtc+Rfsyy/gTD+Fot/aP4E4Dk4seGNUFIU/gmLz5Sb3YvNKOzGAe0jeMsIxTiZ/dgibiC0TZwrZPRN3pKh//dtzMRVZ1NC3GwTFCDr/JMCWuQRRhI8hNPj5tvpKi5SdFK/1D8e5mdnxIncil0aA53dG0ZU8IzcV+0We+fsF/vIQaYjbD2njYNeSqXw5jTstYRU+SFgr6UeHFK62fQRMMz4ul62AY6K8kSXiJwfbnk1HdgbYT37dzo9Z6CD4oqXgudZbJN9dg0MRLhPJNSqGZaGr82XnKX6LND9M1heRAnUjdRjLOEHLYr4qG27cah2xfFjnli+knKGThyilJzlZl/LDGvT7CLKrxq65+HprEsypjKVbDwdYsbSYeWqz2hgi6wkrhmbpRMcEbHIgbkhYSeRiPqgpaX9jx3plstjjTKXYsbOgYZfToOh9MXmZme7ZD/ARxCNMAQ8F41Da6dtUzie+fI0lCm+O9rvw2MKi7V4t6eR+KH5mtju3UNUKG50pKIKzc8jYGuGw8+TUdkb4jg6AtXOJ+FLtWtFA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
