---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBrc4pkDoY3H5meQHaGJFw39iL+RwFQ8pmc2vqC50pHtvTv0Ete1NLNNnbNVu2GABnqNl/xCA6gyBjphHwKezHqI7LBvzb0no1j6Gi/i8pP7q6P9HKGOx1C5giJb/dKvfoYX+85wir2l1xqqY0/IwUlKpsNoebnrdpgPiSMLoxgxPtR7FCJRXlSZmFSay/xD5QeBSC7WNz9Mz6iUFB00XHjqRMaMh105T251o675yeWhJK0el4ppIgQ74sJFU3UOZy0jMmM8sfa3VvvW+EKkC22SzVWzoSUslzQX8AA4KGZ7bBPqvlxEe/7QdOu2NCRUeWSFclw8YbuKkzCXmz6PyK/gn7PFF+7ZT4Hy3rUUEyyPht6W9bfiNPhb3mIqC4UupZEwiOpqFoZZBLtMaN49NDr785mmfYUjpgA8UaG1LkJCBA3BpLr5Q9FLprUn0tI5kCUfzGdhTycqs9Ak2LbIUSvfaM6tUgpOQsTzeklvbJDHKLk9BIkugayX0zX6EmUOq42ERXNuY9a4lNJozSfUPHhZ7LUTxPkGfHEcuVWp18yUhnNLcsDE+g6wGksyn7Qbiibu6qzlBPIuBhyZIR4w52mWQWQo0cQxhEdJ+wzAcjPmLpBCFaG6ScTGe5CCwUJ58w//IEQ9M0S9XwjxMmZIBeK2ZzHAz+ExuSwWtFyKbfZVqm3HnvFGFGsy4sVf+wb2nsKOowzGGTw
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAEsC1LVzXeRz1z+Lt9jHuEhjzX8fI1Z1vbpOoIGLM5Bl1NVHLcMu3W9s1ALSHlD+xeXlVr2j1fa1B/VNKFhT6de/My8ak+NBRpfRi33gHM8P6IT7eqQFnt9UAUI/04YTbtkncNzqVUmz9YGHkM6ZTQ6hDRW8LgWN0wn5MIKRPkiYZjRb0gBSLFMTL8BoywaxkyHS0qklSN76h0QsbS4N2/36DQ9pmLX/q6F6ofP/2EHyccFvjGh2PKmvBfIKI4ohBk9ExpJh5RdvBZWv6d2b0U6osfkfUEgMzj3Lmm2OImuLbUVbn3V4u5bcHYo8/G67mqAbtkE01PbzNqc8XeLPz+nj8goplVljiPUgfE0unbmISVE7KVEa1wqvYmdMO6/l2AvuQP2mxc9pIDnE51e4R6F1l49Ms+DeskNIRRvRR7FVYPwM7+a58LlRR9ZJD//Z8SWzy1R7vWh9l1WM5RRwGDRrsppavroHx6lSYETnC2mZO7uBsWDtRVIlEiX64Dm1NdbazXMxrUa0Q24beIZKyykirl43lvCgPDaZkjySAgQYHpnEfjAp31P2IdqjFnLZExTUtU0UKqD0j3gVdchLk2rHi6SmR0/8j8crBctt96BWlK1D97Nm4Dhku9cHO+KQyOYbr0ezwwTykWYF7NOMHKl8RmUzsYAQoir9l7ly454XBP6nzHogS1sJBC8vsEJnnoY35TFgoTffxAb42s+lCONaWK4ZDCD+36ddPXzFw2Kw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
