---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAi4ve7xHGl9FaGormVqXt2gehN448mP8SPtH8AjuMYTLZPoPG5EGolwcXyX4dQxGSWFX5sj2xHWn7/LkkiSBFdLFYZRMLurwcaBB/1U8hmoJjgfcxCqFgSLqDjOlXNNV3sBT/XOQ0vimBvmO0SRXtzd1722M1xwpqmVhv39IzQT9TJ78/i/qPx38eu5PugscIjJnkEOhEJso2/lEaPGkfffpDh05qATFZWwzTAqGCVZ6VGb6q6eZcR3GZU98v1fvXpfX3tHrQdai2JICIEUBx2k4NOb5xFlTkExTpwZqI55zbK4G98HlJvHg1vp4m7bjQ3LyPFWJQ9zL9bRireaajtJt4G5zgi3qNlBAA9hTtzae3g3kSG8k2UR3rEXf8Zx2izLceoXz9rQXaAwzyz0S4HmXwixvNBVB+uYX82Nng0lnE+IpN0VHLrFh61sgbqr/5XFycbeB7RTLX+Y1DI5RCsG53mCzSHE2VOe3ZBgQPIMhVquDh3FdIiEuVSoUcd4EB6ufcNuYOjtWZSggQ21s3ZcTW/brftEQqk52x7U6di5soFl9ccG5OJcQqTzDgDBll9/kYrlMUKioNaQMsHFVGFvj+6TEZrR6eY0L0R2Zg8qoqQtHik02C/OX46w4HQ3GdupYwaeGVnnRTTcGzP49wmQwsHlfWHE+563oXcuYiB9l9xgBNLr+afa75RfL4D8kJGmAChl2E5TwDglpNldZFdRyMIEf6HavssLn5vFWHAPw==
    admin-user: AgAB2tBQYdYManQQ9MaDH68URrc56HPN6471WMjdc35TsvgfoviIRMVpcBgbRmj4VlnH5tPXOtlx5YNmXcbm5R5OAHjZE7xrEMtwtWXcbh5vleS0xmYsPpIXVKkd5mbzqT4QfFp+fJuYNmlop/Ojz+EPqzysT5AbzYagtN4JCv6+65yJ/tr63gixMvHWFJexq7lRunxBuN+/JCiLuwxp2UlFxcLg4jXzHfjeOMu7soDgeFfRj1SJsFTti4iFHtBo9z5iIpVFrwrIIgujYoE49KY0VKsfNT2Dh3vzAgcC4toE3bjy4s/ZB3Lh3eXbNNgTu1dXjLPjAVVYGiXU5f+ZiKZTgu21pwnUo1iBvrYJRDGtTMOgP5c3OQjlqnt4VNjjvEh6piWG/xPrzyjmWQPAaP8ThejmcriXvACK6RsZFoT9oQb3z230aEO/l5TG2eQyN6hSzh54oUXNuJmQYPc2jQIIA1VnXbOSn8KlVdoMTZ5uQP6BjKONtmDiO1z2thyazcKIY+d84dulQz61wt2mOVRaX40rCJl6Nocg+tSLWWWMBUUdcudP9DftveG5L0Dmvx4x1+kF+DhxsZ7EzINJjrrNTxPW84Mxn2M4bkTdCGMkKtoxQNWnO6uYAuy/dbhPplU6oXPemtqh40lyl+7KmL0Gf1/AfexJkVwAzboEdctC0gjfRSa1OT8F2kLm8DBRwCBLs+djkQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
