---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgC5VdBzjRY1/AOeT/bu2T5JEunAbyex/o/tuNxz7gJy6/gIOwQ5qoeMAEYVCHvFK4iULBKv7R6ipyT59fO5bytNzL5ZpjmtyG7fWideCWZOtZbWTXmaii9gyVJjtyk0D+sYPQpca3FORRAY/Dx2+4IRXcJJfmHOKtcVc8qVBVL7SuuHVjpc5AfOQPuz6rr/tHL6+t6q9s4ICVqoWSvbLN+begfJb5vcSE6k2DwET4xGGUyuX5RdrErLRxTrR/1MUyu2RXyHeriG2AX3hkXlSLAFokJcKBW6u/2FaileQfULfg4rTTGYDyxRw84T21wvhkFm7ATIHwcm+TC7YvK3Py4+Emr48OrYVUlUDCd0ekm950otjG2poV38lrq2IOKO34ipwOp3MjWKkTDxLQBu9ce98c0z3Wc8g87L0Zj8pRKVxhYldem14DJQ8yu56F4bZMZwjQSqUznP6mhKRigIcm9BxrVn9cZTiboukUMnQ8xOXwDLTMIeCHSvtF2YPqCLc4ANPl8t5RfqO9d5gkx+FJjrcuu0MaoiT2cvZf03TOhPwzZaFH8H2B14V0ZZjOH50VWrxsrMTQi8H2P2hHN0frWDWIrBiMf68QdeCzh/50zA2UqoAvb3EKY0xLPdTOktxQ0R00XMXF6c6VdGdr16Z0/i+AXb+b/JvyBNmt85UllOEJ13ix/6Zx2Bfd7BVIorc8K86C95Lybh
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgDFBkZKLIPo/MPWhbjFoJYbejAyecz/zAb1n5DoXla5uQHINo+w1IjWJzy6/eisX1hsYP/Qb18zbdPv+4rl516gl2lH/2gzFbQPItiiQ15wFzEPu3i5EDNjI+4GAWGnjn+Yv79sDGUt2cnR3IOxT2Wv2Dx8tTXH3yS5TwMC2bEnBFtpAkOayan6sR1tgPZRFZTyBHX9AxZY3zJb8w563qgnMxgrmYUYBFS366yf3cFTyAV/WhzIRYUY6M3IJ7/BQ6+75qnJ4AqsG2Z+tOxii1/FksBegYnT4KXsV1bzaWy3L+Du5NTVyW7Z1xaLIcmM+SL7YlMBAgoyQc1rE8ngMogT1UgiPHwKg7p+B5XSZwApwdbl3i3QhY4KKtfxsVlbzCWT2yfkDnQgQHLHZ4UVpEdZww2EqKOx33myQ4QOPGWVOVPxUsVfVO7glZrrDj9R2Mtq+9PaJsZa0hO/eRYiROamq1B0Oeyct3uH8JuEYgROtDbkmW/6Q89xdhKr/nRPD2lA3Tl3aCoTZsCz+QwdQJ8DTcFDWNRp6GlbfBzpxN4bHPEZ9JpjN1lyrncKtYRuWxMbpzUgLmOvW6DCzj+82yx9x4tuiIG+XchWTOCprVtZkwlJ78ngnN/plA8e85yu08vngQRxhqdnKQHxVS/YPBtf/c+MWaQTvwnrQvLon52KvZD6GO7x1iPUhQXTOzBsjverO1FHEKe6VdQAtE8Tbud81u7rnJwhhX1fp+YqBjJ9NQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
