---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-ini
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgA2BUAPQ93oIctfRlxliVUfSvzfID7JaXgFUE+sgByCtn+UA17jjinPVgs+Ue0gQsPoRX0wT3nMxAg7ilVMnogtPFJ7+5hr07IeFYuoazB77U/jlye7p0wZ6gPYZy6acW1OcfYCfvsaYgOqU0xt8YkZrD/3VwTjcg1lF2IolTt7dO+L5JGxFMr9qHda0TpYxVP0XuaWnq9yvxHcp9+IBLqUNLO5IHQ3BNzDPf1c3kPhHd3cbPchPgmRZq+ZLOLJ+6baNz0LELohS0eXhfA/5evt21JbuDZwg7//7Frmo6WoXcz7X8lvohA+Tp4pJ/RUihSweEwkNim2DdJ/bBL7SZsjtbdT4gyt5lgmG5ZsQmqaM60AxBy83UI3yySK7oKdlxIV6eGes/UlliTXP0+vjx7/dtf8D2Pl2HWcdH+1tDJyzD/m6kZkhMbEICGLxMyEbhm+zsoSBL5+MLmTrbtzZW85ARtFqyywWiSAGX1ORDrKYp1yvi8dynL6mTnJec+64rsjAToxiNOuWJNXmRnKlwDoLSCbJRQD7d8rnY6eQTnrdj3UuPLbPQgjAADBcF0pDdu3xLaB42M3nC9U87gCp3mee3Jg4bEjY5yaX7xdZn3T9axMNzmSM9scbSYytbvdUQ7zeJLcyl8+fNYUQ2GhxcQv5RaSxhL56wwgG1Wwm2TbCAV+t4A3FktZINMxu7HaMTCaFYoc7nWW
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBmuo2RBTOHGrFkct7MYFQ+zJ+yVNCX3alTWa5Bkj9nlEFmJkIe6J50S206mDXbHUkMirdKKXEiKumIiHddMd2qaMfK3tjBGAkUaMuKFgSlphyeJ10OMD4R76KH+yRxn3mgV74jDHQ+nThnAeEXDsXciqEO1x4pwpbY1/9Eo02UvFIn1ZuOTHKrWf7WInoubj9O+7WZ8GkIEQvWv92FiRDumNL0uqjsimaj64iOdRvGGT4h/rTHUDZvLJK3+V9VtpIIIjH7l393P5ccKS36UV20HQAF08bioszErZTIHg5O8SJlcHt4cnvPuQaPoPyYuYS5FIQoRZqqn8/hKVe1JR5pVVsjKHtdDarCzzZ3C6rpSOpSGlgtqQ6ARht/hgERqt/5kT/xMciAc39c9kAYvVLNvZ58MWlU0w/iEhywgOh5sqEEXRpipyT6gbEVHKziU6r5O1gv2v9MD+rElxdhiR9NV47sy1LI9o2I05oAF3T+/ukEmPdTODfOWs1CCnKsQdC6/ShPqfccQsB1vJ+akEUz9rBTw29nt93Vg6YyZvVIQ5Ho+49x4lyxRO8d3ZnwlThjtV/m9NU5N4WPYeRZjWm3IBO7Q+VMUkSXLjsk4LPeiuekFtP52uxr0In85/9Atox4/S1GICoF6j6y6kmeDkicLcayVkVgzAC4oxRqUUyYMmo3YvciCy6RMdUN5Pb8n5ywX3vpZ9XOcl/S+Rqk8RVAI3sez8NvYNdJ+7/D1AW1gA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-ini
      namespace: monitoring
    type: Opaque
