apiVersion: v1
kind: Secret
metadata:
  name: harbor-envvars
  namespace: harbor
stringData:
  # Initial admin password
  HARBOR_ADMIN_PASSWORD: <random chars>
  JOBSERVICE_SECRET: <random chars>
  REGISTRY_PASSWD: <random chars>
  REGISTRY_HTTP_SECRET: <same as REGISTRY_PASSWD>
  # Run: htpasswd -nbBC10 registryUser <REGISTRY_PASSWD>
  REGISTRY_HTPASSWD: <htpasswd>
  REDIS_PASSWORD: <random chars>