---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTPASSWD: AgAbuNN3PudS3clj5durMaXIclmdZxvmKF3YT8eCDR0SETa7GvJ3ZdMZj/vj8YRapS2dDSqg/7enGUCB0cSV+O8ZrndpcXMJnQmVSq3uqRmkLR46IFwstSjgFVrdYyUwMMfSw9gde5ipEVPwAFLok+8ZgxJRcr9lwbikhpKKqt7bU0wozJEdQMmRGpXSYnsTLGYmImh5fYeE+90B2/sl1NwacGbVwDg7P7i+N3F0pPTBgQ0ACvEe89utdENeqPBrZJBBcxyw++q5UkfaUQUbS0KvvPwH4sjEEqpmMbf45HamPJMmGFFobnp9dCDQJyjAefqFz/RAEVtxM4/ogfsbfkN/MzbXQxx/D5TBZPgPtl9Vmzg0b72ZKkYEFW7O9maV02SXAPZj1xoe3U0cPy4dBmZVrA2eBtt6kPijWDBFeX4s79fHIYtoX8nyJOylK/vEEXanuvLzrtak7IKZnrNFwLWrHmWlTKP7MVcY/7lUS8ohyIasj+zjp/OCrSWBnrbPeQZXclDxHHcj4IES6EmDSk5qV5Zn9en268H0tCUAT4YUuxcLxZbo5PP7QvD3DQFbR9tX+2wwt7fQqak4wiZZxT2t7kKySnw62DmtK/xiR0gmzHGZkopRo0qMilKbxccUWalgHJOuhh82d0wA8JaVy2ahE8aklx3TTG95FOfv58wWL2MB7fcxFuD7sjed0GUhEWIRf0zv9Zh6aRIxQxW1TCr0xCszF1rGnyJEgdy1Kam+WuMyezvlL4teYGO2VH9EhNAxEWpNsnAAdS4p8kF013npKSnPUei0hY28
    REGISTRY_HTTP_SECRET: AgA0AVA+B+TOxY7fn3SubZYMjnlYIKI3tC78lUvGOkVhlArnG9WaONWlg+uiOmee9Ujav61vdWsNxJBvUp5vOgDRQ1yP3UE+O7t60MaENHiVFW5fB9acxd8lMKvqL7RMrbSIL07cuKrXcSZ9zVPJNbJNzr3B7GUAgbAgB/jymKh7kgwKuz5BtGA9Ct4j3/gTQVdYjIZ9Qxlh7+/1lM7vlsgMvp2Y2RsnZDy+2Ja0Q79A9FimJyhOTaRjEfRYe10oiwW4SYvSeI7Z8vf6GP3CfZsa4ENDpuY2C2eOYYuQXXYNq0ADhlytwGciwqf+72wiEPu+aFSEQ4zicp/5bidYY/fTC7LdTGsaMXwddLbUQv6xznebMv/ILz0Tjb9sBjNYr8g4dCuugqkJqF40Vt57WqnFUGA/fNM1IzKGndpeg07/3NZQeNw1jos0vjZJ0fPnE4li8X+kIkMul5Cc31Dpqjg7mPJqFFAEJrmNdyo5A+wNdQie7ZI9Rw94dIN68MuiP1Kz/negv36PdIgGwiS0nKd5dZbuptjiKdzNVpbASIL816yX3p2ogzuLGI/z7FOuX1bXbF6D+yoWmxJAyVfUrCnqlBcvB5YtLBjUgCVZAi14hAh08ssCULmEwG3YksrBCl/KBrMLBMUGkJmfKVRkFw+YlGzcCTgrePCMOr6WtaamNHK0BZ8xecVXJ88tnFOtl6FWWnuPheNz9F3k76pbIobsdwtihhlJffY=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry
      namespace: harbor
