---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgC5tF0lg8PQmqmHL/zRTdzAavyA1Znu14I/FoZL1ioRtFNMV0MmzGC/dHVY8ielpP2yN43an4sgyvd90VfapQ4rPI5cAUBLoFo6e7AsYLIbvkdn3F8fqvKdDps1gxC0t8DLRQE1ym3/rhdXho75b0cTpZ1o+efdEBZkMmFErC6RAz6noIaWMNQ/NoCKJ2PlHtWIZFpmzJODBBLFPrA2HebeI3svgLqmcplW3psFbP1R2elg6jVEx48rxiQf5IjBL4n4t2Cj7LhLAkiI1mw13XI0wMdh1ygxbLa2v+O3q5S92fSmwjrbhxRb7vAPlhGTUDohuZRkjeiiOjaf5nqPrkP3GiHo38twOe+y4bBLcgzS0rvC8oFCPRui9Q3EPPdj8uYKmv1sihsv5x0LfnK9LAENyaLfqnUPLc/hD9zdpcog+jEHazDXsgbfjqs2F/TLSB8mmp5gWv+RTGPWWZOOcHERv/gQ12hRWyX1hZ/2pgkCD8xAm+cwt5I8p8kJB8H1Wu0VDRgAqe92cDcjEiQQG3m09o1IzLRp1E3pQ2oi7Sbgihr8YBWxvg6ffgBq4yr0VTxSk03F8Zwn4108Q8m3fZtCCuPxlno/HsMITGsCYrrX3GukrrQBQsbzHuk09OiHnT5XXBqnQFaoa4v0n1ZUs1+6Si46zoxAb3or469qhUSvid1/EXUgScXtVmKAfmsbVIpUkxoLmFXX07SOfN3U9EC/fq07ZCwtTBVp6Nu7vmlcXA==
    secretKey: AgCKNj3ERD+ce++Aa8GoaBJaVZ1wn6sOrHm2KPWxNlPbNhVKrefYe4tLHHsgj+wcflRjderEPJ+2YmtqaEdYoRauWABOM43qKlPksvYUo5WRYWrixReh/AMbheW8Fz1Pi6tMQW79GR1DAhsi1JCYkj3w57W1mpHUAUh8KVO63XJREsNa3pq2flrJ8LLFWdytn8JrxhrWgGAAxejeGgG91Qq7gXhY+U5YSm8Mw0MElNgzkg64nIQ7nvz+FoWqIOKlKjaYTc6Mg9R3VpUKaTKS1kAAV9Cb3DnvOIuQTMStQDa1yLjsNSGiPPS/ZIjxWN8wwSymnfF69ozEMjkZPuGc+OIn6Lp8K+IOUDZlzke7DqIQiiW0KAMYjOS0uqkOpJl7o87e39FbxTvpErpDBj9k2cbH21jQgMBbHVUd5JyjGh74CN60d5xb6mT0ktyWYX2XG6/T1dLhH8dSSyieq5+bvtb+/URHe4KDLZyD3uzb4x2WvWvHbxrIcv7vAA+z2WKRlUCR7o7xoj99FfAy5WiEHGI/XITUdi1cCMKfssZB5LP7iZ1X+faCiXoMona4UeRnTFomvPSHrt5m4Htq2SOjhvEeVwFYoEBdCDCgniVAj6qRhp/K/xm3Vo5ESnhC7u7g+IT8XydTsGdeRIa7qXo3QdAM8z8kRJYMVgS3nfxSPCFqeNgWZVuW+7bRc8NwOdPgIRlCjMChe0Qbvs1OTYk/8aT3IKJepZ61e6UjvDjgQXfRcw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
