apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: harbor
  namespace: harbor
spec:
  hosts:
  - harbor.glythium.io
  - harbor.glythium.com
  gateways:
  - istio-ingress/ingress-gateway
  - mesh
  http:
  - name: http
    route:
    - destination:
        host: harbor