---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgC9LhLJN0pNBgQQRS1rfm8S4qVLZAQDzzC66iONSFOskOCamYmZGeQfcmzTYtQbu9o/qQFK6Q16MFo5ILM0jcwq46jzrQaKSsza0MMhWGA5OMauHkoNDg5PAtKdXSN3q3Z/3sW2q9cOJXzZ1BYYjR9nVu9jWUP2pGlSMXn3OUgHmGF/7o8oeuEmg3tuT8d+ARRGMzpUeiXDqs7YF6R9dpRGQhIzrAGoZaqpNFtAqg5iRMzJx2y/MOpVktFSmvqYju9BNq2HeUpDAa5izXfRrtRmIf1lQgJH06mh5g3A9k5yIy3RPP9yvhgN+S3wOAX1LHpq12jz1yKZU9O61WYJNDgCg6KODFM1838L951Avdg9DWqDXNk4/1QMU5eQRXUhkuDX+QRZuQInoyO+NxZmNa8b3w02Uc+JFwI7Ifut/qdvtbwMqkvNujqkBzppeH270qt45uNgs7NFYEiR2aVLJ/C6R++I6KWTnsdOWMYfupMLmmBLqpTL2+Hzn6JZq3/5GB59Ue4069/yLhuKZxJpjlmF6Ei07c35K0xroxux9tCVNP2ZUd9IS5MGZx71bADsk4sgja49EHb9uo2+fhJa4CyWLP9RjEzvYwIUCgKhvkKET4wF/vO3XEeyiji/nzFOPz4LCdRptyQh0/Y+MWvb+be487iuEd7i+twUa918xI8NAk8s79aZiP2vStw6nPfvjz4qONYgXqZYrMUFTkNdmicF/g6wCuYDiPw2GYsx2K5tbw==
    secretKey: AgA38Yl+8aHfbl3LqgeIWaxeY0WO3nKXCJE2r2kIGHyT7vJ/EhXAN11bC7NC/tltBT5pk/+1LRbabnaLrjYUHGyt4gJptHMEejMAHQIIRAiGl1l1+uF8oexxBMv8e+/0/XXaEvThaoZc9VUeneA4WurhE/xVRaWD5XbK8ODh6JPYRUQLrKuMd0YM5mETlisKq70qXsy04XHDC0sj8rrJnSahLEgurCy8ki8FHZCxpLPGs+Fy1qGPPRdKzv3Xb6Yr4bT5t8YXmy5DtsJvOy4hvxXgczewx8r1Qp0/7wLfGKdGzXdg9ZDCyVgC8frzLLzPqrblTVuI2x8bdEtgOQPS/5TP9/DOahifwbEfjboX84pB+poeAAN4iTXXO3iReHC5/cUpWLOX8hPqZPL3ZCUeJlZlzlloBt1+kKIPtcqAnkRK1fkHYnFmFOb8zRFsuRNvLEQwVe425OBP16+KVLxgEkyuTL82wRBUGIKPATOMW90EzfX7IE6lM7cNTjXGCbKJOvDMUIbZRWccilskoebyf6BJatDNszcsNRBX0w+3Eh7QFqkGr8Vm5N9Rqgm5/rrZST36unadsxdXcU43fb7JOHPPF8YQy+fSKQOUkHsMQ5eTC5zPh/Bz4BOe8FoHn/9dP3KbAtdile9Qa76TdPDDTRunwZDAVecz7/XlwR4DpGdSSd3+hX7UZUqD6hqeKHbEgIMjolXG3dZRgpYaG4dsTGIOktJwDcESjJj8MUIcY9yxLg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
