---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgC3YAbLeI+w0Ob7xfFhcoVyob7oG4D75r4fd6Zr2GKnrdiE+gxr2/03ApPQMRix4STeNRsDGRo4DTcWcE0ACpMXcJcraMgGnPbHRSXxG0QNfQyNN1UoPifx54iMazuL9aQXAsVwOuJDG83W9lu7vy2n6yvyY9GZPdmHxhU4/yEiXYBHZliJc8ezeq4Yj50+QNo4/i/743hCT4KzBAdr1fS802BaiPKjxMERYzHwP30yYgVc3FMz2uzAmOt2N7yTkXFwreecjIkJ++yLBHuf6KK2g/d34cdTbOeUyGoy52lqCg+TEjjvKE0MN8XGiaqs/Bnd90G3SL1KK/q42hdplgKlJ+hyEreWDYrQZ2DMQdU6tGrwOK2ecYpVUklGLlWBlQhGGg3kik+GsWhZUobOAUtEeKi8jUbMhDNk0kOjjnx3b333dSr7R8J67w0Spk67YXu2saRXXcQnllVgvKAEuFp9ucI3ezYISkgcEVOTN/RXWMNe0PBLX23ESP+mGfIqd9Z+TXpZV0zAbTn/pwUJtuCnXn7z+jYqFEs4uotwssr6mMnpSb0BxRstgky7EVVtUfGkV1x7m6Fp0IPxKHFjdaqDByF+68isH7/+HERQry3mEE8DY2rrRLHL08PA67MVvDGSvRGsClcYucg9O8Tu9Et9oBFcGFnJB6HdQVYS3GcavoQmtlP8KIXBTYT64hnHe85zek/2ThRcwmODHG+rewukmwIA7w6mn2T1ubpkeBLD3w==
    secretKey: AgB4oSmsGuvAdWqpaMJI3vZjskTxLS2C+El6kp3EGbm7v6ryUx6q5i4U2DjT+eTcqXgYSvrYBgOYhlgU0D3fIKbAGkOKLvF7nsklnN3m6y+Xlgqrv5cU2EJ1Wv5wfDkP/oMYErWzoVcRZdQ7pQEwBYn4tv6Q4+hCERqJuQIcm3r7v823LBBlWgqP8iNEEZm0ghE74Or7TuuTRhxlkkH9znuRahBwLonV5Hz0o8ZwfdFd7Nmz0wksf4Cp6Kq2YTV8i4eoafUrKOJWbgkVXxcV3PWzZ1JiX4BDnOj5Hi1YQ88TLef5WwDm3m2BwsFoNGQYAfgZmj4Eb2szoOLqTgq1KrF/ZVyGBe17tFOsL2dQf1fI4GZrQ+EBlyik+isOOfzmOaCbsT8cSXcOKpQXCVJXSZr/kcVpj5P+3MsTuNtFfnAooeJBAO59zt92HAP9mPzgFoRvD7IYtOHHjQg29ghdSbNGN2i8s3hNcIGfIr1XdOu7aaN27NzwyCCP3nHaYa0rzjFje2hHADpPJVnqhP6uqn9X1ucUPwfYV8q5Xz8eaT5UHBMiB12JEl1EAHXwNrFTwhxLmkVEB8bnt2fB8pGcc7b/bBf6vUAiRCqhmQa4WAmvEgcP97jCzBQMSRe/QSQQF9ma/KdkU2kTlO6mU7z+DyJNA8R4ykwLWY3KgxbBLRVunMgvMiDQFOENHldZwe2MnWls3ljxmvLOjEgHOxV9ZTjB/KGyoorsb6irWBAk6U0LIw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
