---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgBMyPqZDGLA7TP0gCQHegotfEjT69NmAGbsqGoyTo+jmxyQub2lXnC94lkZQT2arMBzlvek83gqfnoDyhlQvYO3WJ+5dDaMYAZeSK0kwraMk4nvhe3aYWVG7TJ9Z8LW7XROtPvHIsc0UVd/UXjjlUzsWw/9S8c2dQ2BfMvxgW5QQRo2AY+QX1iR1FK2V5LMC/hrGXBpCtJjV4QCZXwi9cv5WNTC5Q9+AeSrUZOk1u31Aoo/AhckjF4vPA3E+WddHfqL1tQVFzsepbFjhypLrbiBGBtcpNYTxGanug3PqFF3Lt0Ufx+Lb54+PnM+sX5WAuXqRjVdF7pGii2LMRsj2zQpcnm3G6kK49rVxizKSPUiBb8bE383Gs6J85fhm7j9v4wB2G8+xr/1rS7E+Ayd8DpLFmsgPhSatNTY6t8H/wno9t8eLiVVwkRYVl7zq7QtGbaYy075/tiTu2EisNfWGxOprqXbObR8kmaF6msAvcoYc5itlBW2HiRfHcyWkucy9HEOf1v/+Es4FbMxwd0kvQc76quYN49ipj3l48TaeJlPHG5u4SxAeFRzw1lzlfNPcz2jIYfOhVZuxCJJNC0rU7auzziv1LVqan+9+EIrLo+y8566GKvmYxoA2yHrZIJIbUl1cqgoKzSgqKUqVn75WsO/kunXLxxkhO7EuUaWoe4A7Md6SDkdAx22YDTez5KtSoV6ShPXy4qGYlJyslxiMM/m2vQAxAoW5yg=
    secretKey: AgCB8PQ55LPrTTuUmDNjVhsA4f+n7jQWooMhNTaVToW7f7tnlgSgOLSqMwq9D++tFeuwzD1myJw3LzGG3w3vrIAsySUgRazC3/KuB2KC59oY+4z9tXLUVog+4nS7HloIGeyyQRQ/8JONOwNB7aARJ0G/w/BA5IkqROuxTtRgbIUH2bla4/P/23SocDU1sc7t0IYccJXb1L8D32R1OA/5O7zspyPG2+SLTl9khsYeMYcz5s+Pc2t8VuTDIayh/Dcq9eSX1+c5LJRPZWcZUlFmQH74GegWiZr1oNBgrQS9ciQ9t3ftlBe5Aut7QwpIjBOuoTaC+3knp1QqoWg+GrqkAvN2llXrCwOEmAWbNGZPm86xxdjrMVw/0QJCPVieVjaMpC9LULb+ycMsJhrEfHvdmT/HIqMWL2aaS7n81lKcn5Ml+0Fa70ArK/W4AKbidNqufOUKtVtr1COfQr3IN6VmLmiUfAxA6ZicOOkyVNlsgS4viVZrvUrqUb/JsStcZfpSjusmVx/Eoehuj9vAezgMyKqww+XN6FBDi3/20+On/H6vvFH2zxfDVCheiD6QKrgc7QpQayywcyU+UQJVA7lll+vDEK5T4yYT/aDr331XXThywbTlRE9D11aWmZi8lgOzAgSsnKhxx6/TIti3aswZODkyrUqghMzAoxym5eePQrq7Nf/qLq4eRMwaeFLXd1UpxIM/hxp88w6/SIrykUk4KseTJtwPF+f15lI=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
