---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgCo5zPCTMwo8v18at0yX+lohFoXLS/vfgE+pVMAhEc+IagclvrcAtMmmYiGrWPZmq209tzQHJw29S+1HfASVFkVBF3hJ33a77CrP244PZ0gCzMPHUihghYsBtKQpgbOrAunsHYkNHlznH3s69SBQZPpMU4/aKTYvmpPI3rvKJHdN1cgU7awTSqF0K2WSuDOasqsb4QkiGTle1T1/EfRLtWOhQxdvBoW+uKxY36wcN/iNJ3uUKVAIAmaMDahG91U9r6joPMOJiHHB1EhYSTxlMS0qu6S2s+00pA5Mj13GRnehu+o24yehBH3X6ivwEvE3zIXaFvaKoKOsBnwajyxhojMlJqBRANNxW6P0xpvdQp1AKYqtvdRJbtYf4pYNY8OMrrlYcomku7vQvR0+i0eD5TF+rr+IEeQ831PigGQRG6JZlRNIfXAwYwiqXb8bXBC67AHgebri2S89SwVNzL1pG6/dnc0vgoerWB/1+1MrACmy2ZSHcdtnHfy0XMVu8OuMammfUTcx2L6aTwc6Pp7CRaKfZimarXOQBtYBeSFVHcDK3WY6nzH1mDYxJWXjGV4HMlxui77XHW8gPo+1BgX+PGIPy4EY2lJFhJiD4HeLfs+kX9fo4PKlcmO4tt4K2dy4mp0/8pengyDyEU3073ed03dPmCP1LD+av8TQQbF9ljiyaprmBVSviRTwQsgFaiLCwI41a3za1AGWDPxRP1w5gcbftwvxH5o850=
    secretKey: AgBHfUHUkJEaNeWO0GFm77oDO5MdSDQvlgSg4q+qzjoiHhE4kv01RCYPlPWiqZiawhGSgItZx19jmv2AeilUIxF3R1ep20r7Y1w6sn3gkfhAbNiHd3uh/kPAFZN10WxHb3FvUFYnlicv8cBEo3WEQv166REUvRQSgh+TZPe9r8bunolff3L9MTrSiispv0hkV9mElmSt7JtFzIx7GL+Xex3hvjfAZeGkzKh4W+FmEA303wsR0ha2UDgsDYdCDqpoleEAQjKbgmmgmvcTlqm4X4uqpsBiS/SOJg+nH6usX55gKHOXqTLcHpUueU5HP84G22KTSJm3aGZaWvvVfcm5nipqrR0bTtHx3QvEC9yHV8n3ZroEYEyYCJ2XLrOGrizLMG/6Ivtx9i3ZLvbDROxsuC00mpTFYAbT/2015UiClwDb52uclny74IUp0J7t14zZm7w/BAZBrV/jGt81SNWEEogSVADOziaHLTj3lQMkEqd9S94J8udSCQqFUrd71564xPiOUg+m1K9xzpvfyeaa3JkJdsyxh3+4aV6BWNo0hpOXdaJt+WCzL2hru8O5e9gC7eTEiNXMdwk3jv/0v8CCaPCPOqrHU1gwgRWlNCFZ0p9u3Ux1Z0zqAetCzFqS3kPAaazChv/91qXII0OepmvGcysSTrj5CQbA3mfk8C32h5nuc6rkJQ//tuB8KOqmJXPWrFou9MIuZ6EYWMppi4T63NtcdwHlR1/6F8c=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
