---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTPASSWD: AgBLGxA3wBXSM1mMw7kwcdvaXfSESa3zBrcAiqPD2p1dcLYXkRhihFey/QB0JiIPmfIdh3L4751pLfYibLrXRZARu35MkHCCkyw4GFIGpVQzoFr2Y1OzlXK7M/4eZ7n1+kzF4s45Xve4q6mquarKXR5BqX/JbUk1mxSPye9t+Bj9A2v6dST0ew1OyxmmVI/VI/bb/XiiIZcMKQq2HvOgIj+gt4dRPErE70i4dvpN5pBrUOa/UwiEi+BVm5CeqXIy4obiw1dINlHQ7txsZb3GvhmfHCU/2JMm1DZ6BVVDyX8kep7afbHSN8GY0RRsmuizxT/6ihp2FGVmoAlpCH+OjgHUi4tgjZjKviwvfaoO8X2RZ16A+uJ99PYrFpbc9CwL8yghQTFf7l9D6A2y0VoL8jAc3TdpdCkVfezoiDKp2KORDBGzC7AcL86/Pf2ywvvTMJZsdnCnOkBJY1DNyahmWNLE1+mHbq58/7lqDLBrm+K9bNT6gXPYvraOVTlrkIuXSxmhUkJnUoViF5MVksP44B3bes6qngHNdGZHq58pB1EZWyBLdncJAVKPNqbHgbcooOeu/OMKKXWHKgQDKulIxNQikQDLujf4frAjoaD11Ho4X2OZOfVlx20i00KQG/TrArLoZYIkXUHYXEquYkqfklUYQqn4wHSyI13jFTWjKy4rz4L4ESUxng6rL8A39fjHmVQPllHznWzJVjSCXWACKMcqkCAqqG4KQrHze8IEtgEQefniCqkTxVRuN+7+TIWt6irhKTtsRcZfDzRDfKlRivDZPKNc9BOs01Pa
    REGISTRY_HTTP_SECRET: AgA/lrRDniOqfxamYNPY5NdQ8juNTqEDWj76UIMbLvdql6w2rVRCXN165KUJYZC8oB2UtEleVqHCizFDbAlDnrk20x7Wq7z7SbnheQPy7SQkLxf1epxv1axCIhMfmAsOj5tRoFnrAJB000ko3boQIQcNXjzaQUvh5Md7dUIhAj3njSHnJmUgFmep+ynqx6DNEBKKeV45xdeHkXTXcwcO197BJjoVg6Hg4TGr/BureEHybSVv5DwOkk+JTilyp7FoHSEAHEADwoztXUF+5+CGgfk2FykoULxTPA+uOyQOaPkWVsuJyPq/KpifqvklIYGI4bV3N5AIdQ4EJ5R4e5+BNYQ12M69keVOhdWascgNHU7CqPNqRfKOATaFh+4XkDA941BFp+f5kqcklzUIIckWsEA8s+H7TXK7F49fSjkseQSFE5+SCzoghQolug80tXOHjLeC6nzKi8S6Cw3nQjULTA33Z1uUVIOE7N27a4lSoBdU5wyuyV2RQrR6JaN7OB/3h+aSjZQXdYBG+LmJTVC3tkBJVpI13P7uVrmKZST1G+pYIQt6fDT6xEhDcb5ZkrEmzuDwVdScNVdj1ufJKmzBnkJEM9tczb4dfiT8tDTWO1EKtCPZk8rG1yFFGeNyXGu4UdtyIJdY7rPHt1OfUIr/HyWdjAlTa9EM/opUxdU9lSpT+VixHE/ZUSVGIB2fP8srFvwuxTDjZIPrKhG3wy9KGu7VVTOu1jjU6pttDyFXN33FrA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry
      namespace: harbor
