---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTPASSWD: AgCPGwj9oymi/+Ci6WKW8kV5eochwKAyHmwcx7ptUKRr497g2tqCfZvbzXsQ+xEOG+Cso6XMNP88ZvGhWp+JVq42JJCm2fEr33dN+R2YdbZ7TGeV2lgWVJ5ljauYTPvKamNCqjBffgB7c3pYGjtYf5toIKe+jUN8quLSxyymyh6WWA/FHJ307NWTk0txV2sIejyzdN080Mamr9xQIefXx67NbHmS42zp1c1gTOPGpZLt16PymDc5VaQzuI/d4DM52fyxm8Xv4XViFvMZGXYlz8r7jLEbD0qZUSMUfV/lyyNe6oR7yKvKlxyqVOZvpLN0DVozucQcnnf6hxx0juj1SX+s3oA1wgVbyyy0Y7SzCwg3noH1h9wLMvNSEEm+I5z+KB1fFr5jyg11zCqFSTWpDjsP845UDt0BE41dfo+3W1lH3HxBYan7qEsUxK3t/shXHb6ablazmRAp2yVgzb8BbT8dZUraVBhtPq1ZlGmGe9uj6VxooxgvBvCmWrhZzN909jCl1mEV9f2w8xWbNeCtDSS3e1rbKPgmb75vBX2VkwrUB8RYExPaEIqXvEMO668ISft3flp3DaITc4kGueEvjzEfPhjWU8CnhTXA68t7dLu6F4/W/UUtHgC/C4V5NnAQqwH0F6/mIiitUgiw785FFe6DONkn8b1m426bUsbo6uW5MWQwyV3AwmyKfS95iXd9CHJLqgrjyMjeyb4YoM3ykv2bRiG+0eDpVKzO9nEYOgZ+wrtP6aEAZ91ZDQRsJ/GdwhcNEoHM2MCNPeW5Q+0xp0ZdxkZdgmmGgkX5
    REGISTRY_HTTP_SECRET: AgBPZac5TECxYCo7KeYxrZYvx7wkDsbkXqSU+7ac302EHJHUIfbm7yiZ8e0smYnJK6Ta4Ux9NjTdOEqjWdxxbi88RZHwpVJ7x2XXuL8FfbfIxjkTuOo2vTYlRoUYuVNgIebs2ftr4tDQ5K6DWzttKapm8k1/TdLp/hIHrg763dNLKvHCYfoi+QfCEf+44EzKUmQ3XBBpaHT64YPgxmyONgvrQNSwJLHKDShobZCC+PR++X4WcstOhnDFudBAoK+J95ggeAHYVWMdH8PQ9AkyDIeG1+XLAH4EK8rPvWhIZzd4/r4ayUV234HZ8f9lg9wWqwM6BKOgBGg8BwpGLP5fek2FEnPbjDNIZZcdFBfm70EerTxvxsF7yawzDp5dYnnaiTYH6Ta9Yhm0CBwY/sHUKHcZfd/rFKiXmMFRQCDVeOhEVqhDvCnKyUmPDYisPkyhevDwKeZf7T7/JUQTnDow8zNpCvJQYAJbXL+TEPAGCe89Jp7q2CV7/bD/48TJ5lo2zThwi9LLe3gyv/f2aiROsAlLPyus28lIfJtz/r1ENmXwkY4mcgeUqLt6H+OE2ANF7Iif94x0Hji5UsSRTUWd389AjoVr9stWtmc86h9suRNNANvzfMVxs9ls7+BDF1bdl4EneS6Ypgf/SDmttp1Q41n0gKMU1cTTz7RnMcODj9DZnETKJ2+6CHSLRpC3ekHPfV94bd98MQEaPPGACxBNnf3mqhihuugc5//7x87Urjqe7w==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry
      namespace: harbor
