---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgCc78aNAQ1mcVkgyKDuedUKL10sqviz3VMAAlWzqAYjFrcs86vKcyil8mW3bPFdF4YPvMJRFvALNh38TDOlpWzKdSMTftaEsmjuR9lvdyOb/HdHw3A1O98XODyX6XvW/kpNcnxHt9ZB9ipE7o6zd0nWcRZr+8s1EYaI6yAMDXmQc/m+YiPpvWuhlhlBZMKf6OEqDJISfMixjAIGuL32Y6EOBFWbWy73gbC39hu2LKRXAbPIGaQOsZ/+sIA3900yVqFtcGog27dym/DkvOnNC5HyN2+ZsVHuJO8VFvG8Q7TX/EwDIfeQmRWggKt9bb4yCPliYavCESV2cTxIhCCdsgigOzno0Dwqctvp0nWDTECDcS+DTrE8VhMST/+kb2vOlyMTMkQxyDM8Az8aJ+jBw0856+/CsLFLOl01BfyEbdj5SJULPkZElvIUvhqQB60pA5XOgDxA14D3NqktnYKaWf2hI9TtskLYfSR71wlGtVj0nedoWlRMUtOt5Lq664xNdirS8w6Z5kPwmroaYHBBeGYyyqKQ7E0gnrl9UESDn0LqgGBZZJv/YX4CDo5J7nXBmSALiR7mbWyEykipwvmfO1Tl2/y8R3MiLi039SWwF7ojUGVy4R3ORyfBCR2+YKKKygME3ovIW2ramjMqGDnoIG1w5kFwEreHAorZBVg8AOxak10DzA3UPMPgmlCuzkSb+1ZKIc07WKNVSIlFF8Bz/RN4JvaLogg15C86BqCOFHKd4Q==
    secretKey: AgAjax5CbqbLY2jUQRqmXQGcZvt5/F/25lEyGjCgYNT3UrqM4AfZGst4KIPOvexl8uSlQq8Z4o7PYyc8vXW52hxFJ9ySYRLtCLH5J0G9vfGTbIx4Zqfy3T64utPVHVJ75Wz+6NXX65jc1loRAvN6ub6kN38yKdyAysoUxtjAVRMPSJ5Gi0ULTlWT7IpCAfVesMpaWORWx7T2B1T+c7iMEaCl5IIkjW6uSXtrtSlqFOaOBl3/YX3liEqID+O9+4OylgqfDaLf1ZRlhyZt2cjQ7YZobnSdmcCg3iBERODfD5QgFkc/1kj8bbUFZMEOvJGXcNEJCRHf9d66eogHvTuQwCF8VhZ7+fr1BPlEz+na6UlcJOCBrbVRrpNW4axFN3dBMC+eESpIc5H6N9jSdIqWqyweKIan+zVbcK1a6sezZeRkabxfMZSCC9DFz2MnDYmTkziZF+QayGwzqn3t31QmrMxL/702pv+bCBtoIskW2d8prwxsF/QFTu+nn8FDBXWEDAydRiSOornsorII7AM2Y+53BWizC6zz1iwEPzC9O9N+CjYKW0i4TiC1dHsJzz8jfeWeGTDYSea2SodVHwmoX+LyzLhHpEjoCK+Sdmrt4+RucwFV5IEvZ32IFpjhyu1XjC1R8F3tMRt/1uiFc4t8wilXiSqDkxKXjK1XKgNWBXm2y9VtciAihREqwaaSrFaStSa3JUfl9tVmecJzYshsWt+8xVizxzP3+bMJMa5CfMCU7g==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
