apiVersion: v1
kind: Secret
metadata:
  name: harbor-envvars
  namespace: harbor
stringData:
  # Must be 32 characters long
  CSRF_KEY: <random chars>

  # Initial admin password
  HARBOR_ADMIN_PASSWORD: <random chars>

  POSTGRESQL_PASSWORD: <random chars>
  postgres-password: <same as POSTGRESQL_PASSWORD>
  HARBOR_DATABASE_PASSWORD: <same as POSTGRESQL_PASSWORD>

  REGISTRY_CREDENTIAL_USERNAME: registryUser
  REGISTRY_CREDENTIAL_PASSWORD: <random chars>
  REGISTRY_HTTP_SECRET: <same as REGISTRY_CREDENTIAL_PASSWORD>
  # Run: htpasswd -nbBC10 registryUser <REGISTRY_CREDENTIAL_PASSWORD>
  REGISTRY_HTPASSWD: <htpasswd>

  # These are the default Redis Service endpoints that get created with this chart
  _REDIS_URL_CORE: redis://harbor-redis-master:6379/0
  _REDIS_URL_REG: redis://harbor-redis-master:6379/2
  JOB_SERVICE_POOL_REDIS_URL: redis://harbor-redis-master:6379/1
  SCANNER_REDIS_URL: redis://harbor-redis-master:6379/5
  SCANNER_STORE_REDIS_URL: redis://harbor-redis-master:6379/5
  SCANNER_JOB_QUEUE_REDIS_URL: redis://harbor-redis-master:6379/5