---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    secret: AgAOWXCa9GqmwrDv7vgohET0I/yC1Q5Ce72e3zEBHgEpp4YCyKQyV1zMspwzquZkrH9uYcF+aJRNtWEbAVNR1OLWE4nZBihwNLIiU1bi69vfZsrX3vZANDsgXzfqB8MPQSA1zTaOE9Zpk2ch3OLo2daW/Ic0LU8u+3cAM0pFfDUmXowFdgepw75OHDH5iIxoL033mGpP9mleYxw+AYKvjln245MCJzorHt4/g3mdwCz9OB19WU+/yx2IZ/rR8HqwLJzn64x38qN0+2U1H6eHSE8hTrlPvYIX5NYJEsejyS6POJ+dgKLP8l5zsqyHnPVBWIE/AnIRGtpKi0/oPFNfnBkJjbaeBN845II0MM+csJClpCv1zKZEhacBHe2aY6MpTViIzGE6ch1pwIJvnx0QjWRT9sH2FUOWOPkApgqvl9dwZukt2ccHImFkfO0GDET4Uebu5NAGURYRbhvkm+fUy/COJHKhz2Sf/bB7PHgxVROSoXIPp7pptuSVl/7YGYJVGqxqBB0d0u95XRXzHq1VUlVJptNHgDseqI65KhCBdzgwizmhmc677hoBYHJZcKS30A9NsjkbRA0ySjnxWPoNZoZm+yBg3EO8I0T4D9dHzFCWo2oUXnGQgHijNWRfArUly6gMd1pXtxmwWII+YgYSVITH3Ifj3TkahidChZ1WHzkBYPUH/7Re2FswmFSO+DcRPgu+QEuEiEW1IwYS746icklA
    secretKey: AgA28Jy1mDkxOWSCCD9PcrT+COro7ebcNGf7aBaY/Jy+sWBhVXGCrGXh7c7iUIcHqlAm3cKmap+fB6NI6RVvlRCwPqaNX7tGXT9aLmn5vpCNe8mfJgBrHFkvWM5Vy1cTDGb1cmMnn7PGmaTGeMU8ZFnnI7fhg/VQQ/crt9HSqnPnp27i1EaT8wM4NBv2B4tcM+GpsE+OkkZwFrf8cozGNmXoP1izEoiY+pZClAKVUgW14CaMpW76BzcCDDaqZqx6CtFDwwmDgxkx+jrYgmxZOTIP30cxrkLNIy9WrIrM8dpjdlSZ5otxCKF8xMQQA/S1cT/DPwkjYOwFj5aj+CBSH/wN3BzFLoajMpKlg/rakzr++wgjFdHyFKqkBpV8QVatLnX0b0dqf91U9EQh5TS414ZEljH/4GKWGvW7MVNRCUjszjque2KbTAQzchAa9S3usl6wrXBTe0gKt+Ls5aOSI+siYJfZCe/TxpCv6RM3kwEPbXtnc7IpsDWzq00X3KtLnhiAfVFYu6xeDzpddHsXKsObcNqmlqxswEW48hqOWaVHHxPmLDRf1M/NTQZuIaTDcM2xizBraOkXYmwlMdMlW15LekjZGXpMQ+8M3Uyz8TKkFWECGVn4SIc0+RrPtXnASFuIrgNALcL3ONMMbfj46oQfrShBUY73nZkxdXb5PLJ/wSN8gxuP99v4q6ZUxyo1WqNK35UaANUh+f6S95ToNoKd
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-secret
      namespace: harbor
