---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: initial-git-source
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://gitlab.com/Glythium/k3s-pi-5.git
  ref:
    branch: feature/istio
  secretRef:
    name: initial-git-secret
