---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: initial-git-source
  namespace: flux-system
spec:
  interval: 1h
  url: https://gitlab.com/Glythium/k3s-pi-5.git
  ref:
    branch: reenable-services
  secretRef:
    name: initial-git-secret
