---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAuHYRxMBJ/WwsBEwahDHT3OBiSAF6kJ73vul5Q0n6oOBnBpYp0FVcyZg8gN1IUvX/o8CJM+/5C2l57pquGe0hE5o2DfLpgE3MwCmrgnBb0g4U5KksnzI8LvZU+cO5E148Dg3hTMBKANKX23GDxdW7lfHzlBucjfV+5kiYKLk5yyJQZH8mYVK6Lewj9MXFLjulrhLv3WGBX15KlEovkk/kyTJZmpvYmVS9TZrVHzXGFE5Pf7sNPiYdkddmyxaJAnFOd7KKxlMB3kaQIpl1ye/jCE2W/otCdusFvaa3kgjq7VxkBdXbwvGFu0TouhRxgBmo72FNotsyPP37b/wF/F9awv0bro0dnLLoOmrAJFMvTS4b0xeai++Z7tOniZDN92euwkcOOTaMD4a6/GwAKGy5GdKBpk0FM708r57bVuniun4A2NGy8EpAWVWPb3bFRPJ4R/GSw8Tc15Fg+XzEMdEEkwxINqFZ2seB/0yuvyugtMzhZVlqVc2G6KW+M47rk16dQyiPfqBcbXRjf4iRHgqBFqMk319QwdN6U4xWVahSEICcpfoRuoFXKo8di1l2DIfpgcZs0nUXsHkJQd2VjpyLnowKRCV4tezEX99kjFJBkstb1mOT2VXRxKcoBCfaB1QjZ2wg7u5KCSNJSCFN6/1gu1pApQ2/A9jHSy0HA4AcMzdqgoZBjpBwZfQXviOaXZ1zLWM5OQOo1hbyyJ3ct606EjnF4SmodRBBErdlOQa1GbC9JLwNzeI3W
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
