---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBHa1+k1mTM0bwFPM0TlO8gmRWXO69QQ28nAQ4MVczbSSO4ah+zh/J7C6IxN1c4xwhkI3E7be88fKbRNyHQLz2sMrS/GUneYbS0Gpp8TZH6hg7K3vxxb+zLE2YLeRImHFWrYd4FE3p0w9YRXpVaSTVFbGx+HIfu+Ni2YvygjW3HMy1jhNWLFmGg/FBczb5rPjCpuLiKwBDukeqNfN1RID82FEOSuCuLsQmvCv1ijO30cPbsSE7DPriO9vh6N1Lbbefhh8vUQeCjX0fn5cXmo5ejc9CjU2IfTy3xuNUzs6Bf4J9hiVrnft9hwDtC0eiIhtZdO7NHEoEcFCvFsWnfncUpRNXIs0D4KWP9gTgcszfzATbpuEVmMkp65Rg5hSXn9G9y4nxhJ4F9a6KOx1vNlvlmm7u7Ti5wxinal+MEQvvlC2Ls3PG3U0QKkE9n7kYjucfc3NajJzyBelZTyfWB3q12XJ2vxzEj4eJd9uKCOQJNukwhJ4X1OV8ebk8Q3Y+v1/ZfOcuEwL3fThoKZjLlhiPwxI6NTVuIWYbupBbDteMfKL19EJyVN3Sk25rCEb1fCAXtia5CXRn+TNsl+xn5eJUs+KiyQcbElVIlUZ9qGbkjpGQtEw5bbNWrvr0lu0TAmustdiDuO3AOd2bklEkU2P0FoY7Fm228SzHOMFg3fB3bmZFG/znzQqiAJrNVioscm7a6bTxujhsRazC+HtSjwcIK1pLEzr7dCeUvTqezvYkG74o1ZRVx4N0F
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
