---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./services/gitlab-runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-runner-post-install
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./services/gitlab-runner/post-install
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.gitlab.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  - name: sealed-secrets
  # - name: vault
  interval: 5m
  timeout: 5m
  targetNamespace: gitlab-runner
  chart:
    spec:
      chart: gitlab-runner
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: gitlab
      interval: 5m
  releaseName: gitlab-runner
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
      clusterWideAccess: true
      rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]
    secrets:
    - name: gitlab-runner-token
    # Raspeberry Pi 5 uses the ARM architecture, we need to override the helper image to use the ARM arch as well
    runners:
      config: |-
        [[runners]]
          [runners.kubernetes]
            helper_image = "gitlab/gitlab-runner-helper:arm64-latest"
            namespace = "{{.Release.Namespace}}"
            image = "alpine"
            service_account = "{{.Release.Name}}"