---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-token
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-token: AgC7rWbza1ewayElZVn5E5e7kZUN2yK8dwsiRpc24/qApDx6EivkSGz7FVH/vHEbBQqPCUHg/L5q/ykwNYH6DnC/uFhsrtWBwdn/pxSby3CGTeVPnBrI+70vShAQ6t8uZQfZGKC27gEuW+/3ej6ynMPkP5ptmRm84rfhRcqiOl8NdGItXokn+cZmwFwVuzJKwUf7KV2cyTVomdFWo+mw47L1w0XEpCnUijvQFf54f/xr35p/2FuNFd9xAzr9BajE4fkO4AfpMoAnk0bjWVeAZ8CRAV/FAREXisvzuYvRODmjs6ISHRwMy9AXT4LjRguzBBHPm0UIfveCAXQAP28c3Cx05t6ICaYCD+8MPeHUp5qTIURg01vHqnLu+2a/UhUYd0CdS30yH2VMh9Tfp7CJBjt6yRWJ4TuWp8UZS6mfFHwP/nxl6ABC1odFqV+9c2TJ8zUKa6ZLzSmTCihLtbn1DrM4luqYP58igdeECcRlMs0r7CdSKAk9A5shH8HhkPdH1JhHTTynPsMcr1D8rW+0cZMojesUPzZ6d3lnae3My+9GbM5HOsgn2LDx7TGiqqhXVbuWkmMDw+pK+IMfSDUG+zCxfKqg1vQQsI15REWzksTIkVHzlx9Z26Xm8Q4XEtwcngoI0xCQ+SGVqGb4fV8F0GDWHjHvWQIQTVrQIIqt21iBkrY9mevaCK1ipVYGg8ltAXbN9imAefJ2BcT2+bO3gYmcQQYM/aO9DRXB
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-token
      namespace: gitlab-runner
    type: Opaque
