---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  interval: 1h
  timeout: 5m
  targetNamespace: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 1h
  releaseName: sealed-secrets
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled