---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  - name: kyverno
  interval: 5m
  timeout: 5m
  targetNamespace: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 5m
  releaseName: sealed-secrets
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    metrics:
      serviceMonitor:
        enabled: true
        namespace: monitoring
      dashboards:
        create: true
        namespace: monitoring