---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  targetNamespace: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-setup
  namespace: flux-system
spec:
  force: false
  interval: 1h
  path: ./services/redis/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: initial-git-source
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudpirates
  namespace: flux-system
spec:
  interval: 1h
  type: "oci"
  url: oci://registry-1.docker.io/cloudpirates
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: redis
  chart:
    spec:
      chart: redis
      version: '0.*'
      sourceRef:
        kind: HelmRepository
        name: cloudpirates
      interval: 1h
  releaseName: redis
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    image:
      tag: "8.2.3"
    auth:
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
        
    