---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgA9+o4q0N/L+gB0jfwC5SU/L3hlbD9TKZhXzC7hQwC7pXcItKmoWxDyzcpPqCZPBOKulVd+BbkHEnHVTMBK4/JtQeuKVfThUcZg2UzV/ezqxKtAVFDVM5VICct7LZORwChsVrTgcWGowBxj2VjtpC170yZ6BMHIaPfmbIudvQFxZUVdyzWng+Hdf9Z4QItxuHhUSXlHv3Do6jsGNJfel5Qpms1ShWJ8rMwwDNZQ96aRg7J6hh38eSlEAncwLd8RlS7aJfg36j41SzK4nwZjoFepjcYRCn7Mp4b0NIjLTbt+WNTZS2muLIQX1IAzzNEl2mNKWy+EiQr/ZVBjlKJeFLzJgKeLdmtXfCbrCNbUaIBK3DiTyzt6MBms2VfxZR9EgsGfisPKPIvQO0sOzDeUc7uhkPiz2VxP0TJl28x6rnH/40ZW5sPF10PQEm/Sonn9eFCpT6jPhHdbW/KMMJt1UJQrd//A8pqbkIUpl0gU5gsgWGZlKRv8KKuYmuJI5OT/LBcXYhne6+fkP34IQX1YXGlqwUVvUjdfaoffJLYowEpQKr5VWMahT4ainCqOz8Jx9Vlxs6znw0i2r56dy7g5LXVmHNcqzo7MNlXeLcZxvm63gy9fghkGlc5AhMNp42VVnAhNiQOchIF4ihB1HYmPH1a7pkFEbVT239OI7pVewNi1BHvXMtMc934smJcVl6YM5X/FFOZ4yvp7K3vK4vJMIXJk4HKYp329Vls=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
    type: Opaque
