---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBYqis2S8sRBEt4B615GvcP8eSgOWJSkxnTt4FzISVuzctDrIe0FSfbizguI+DO2H5gmfMzFiU8mJ9J+q9JK5h3ycg/sggk7y5iNAAd9w1upp+vNNK9Se6THwlY8ED/xYQpqOA8vU2M3N8QhpFI5A3DK11+iLu6CqPXMCifbXtRb7ovbmCiDXB6wB4b4MR1nu2YavDCh7Epky0CUNcPDP1sjdEjb74z28BldnaLIzG/57zNas2Z8EvsnNVD5ciXkh+Jtpi+zPpt/iEOa4e+Bey51yzccFqZg3XKkNS9JhRvuvKLqCDxTYYCT/mIrScOIKj6G2YQpH1gnQjBiBg4Qae+UxNq24PsL3uEjOxYgKqOu9Y4y5N2uxTjzdFW3P5IiGxyzBawAdBceFdt0tOgpM1tdKCa6xWsSufZhc2z8EWSuMSl6zyGUGT/LB9txIs4eNnywnDy3c7p5C9dIhV9wKHWGPCy2tKnLGb8Vpgq7fSS8SnT1z5UUp1fPKc3YBMfgoI0CVYqkOr2F4lEOmquG4RN3tN6fpN1krqZ5wKT+67OVh9gfsQqSSIclRZFH6iHueCzq8V23LxO2fENt+DgWq6bYksQBiujQcG5yPG1e2qMANAYqQBbuzAygjUZyamYIhKlffpoy8kGAfINUtLvkAf0xkzZy8EeX3wKO0uwZIy1G92LIk8if0Eg22AVoLEpO2S78x8DVsFxmj1R86JY+S0babvz2S3BnkY=
    postgres-password: AgCZLDoyMr4B68S+BhylJ3OcxRq97CAoL7GorHK8zE1J0Qh5qNa2yR1xfaIgOruM4UeXRkff5a6D9+IJPNM3mP2hXliGmKn3C36ilfiFkXrug+V3ElqX1G2iHXT1vKkoMSN9KqAshrnsyTbI2YPRAK6+WLHvg4Eppel/9Ct1ruQ4cYAm3oN5RByj9cWFqAfytgcRANemZrNiVA9IEjgmyr19kHte3JE+AR4mFtvlNMekxZbgc2I3f1GQg5w6r6dNB/V34CAf1S94qp5MTptdH5W0MbXHXTeLaKH3CZnU4ttIK45AQHa1XPc1lW0FFclclJTHN4JfNfHSZnsuUgMGDvbJ8RnKoSthnqYjQOTsHHuNPxLjCmV86pH71pL1WySRcA1gTmWK+fWAfPdcLVfbY9WAnBHXMGsaNZBHbCR4szyc2uSUi6ryrJuI1agXfccsUCuFu9g6iOzO4tPIXydi8WpWV6T3PSuHdUthmh0okJfAbwzxmDHALp2Afn4/XczEIrdrl1v/X5U3l8MGsV8HEOx+5a2B+M2mD14Xhs4oE/zoShn3Wi8wIaH7OP1nWtciSW3jQEr2ZPg/GL8CY79bAuql4QE5vZrZcE3BdfEUlVET6GV9kmhWdq+a9dEvYBX8zDG2V705FlWKa8A9nadjMg1wowOE72dl9yDBPYZUeEtVieRjLUQRiHqK+Meo/wwKcvQ+HKqEz3f0zao0Ue9h5jACf1NKYhAubo0=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-secret
      namespace: keycloak
