---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBbVTKdIIF+989mmBqj96VCzd5hWkaViOr7XHQ3Ta9bv69BeyfXGJ0fDhoMzh8mDxGexzw/lmuXrzm5R44BONOSp9tHjr1KJEytS27vXnUGrO3TNrXu49P7KxgAVgCVp/VUbIhiK0IWFWbi8KqBpN3yuv8eqV8xZFbQ7CcY0p4USMiaC/CoNAYyXozQSe+5K/6shYG+6NtJmrRrbrklWJLnj70NycMszbdzX+9D2QAbt0QU+9xSZw8OtjAd7Z9Dm1iIGbaJPbQ4I3nCyISIVIgU0oi1Vh0+tppjg3wtjeYhW8pX+Aijhkjy4yAgMkQRRtjgonG93bZdtPLk/M7rYgiuXwsOTOfoHW1HZnl/xoRhIeLcUxWySu+XAHGx+QyKUrUtCqa2m0Pf7a3LZoPtTvKRpmSLCAJ0b2gB25AhKE07HfLlUV3X+DHEy6w+r55wxIAcTL8yuAM80P8bWfyV4p03ocPsPmTIzr+OPiqn4UXHiiM1duLAyGR2J5XRazMy0XOe2ayztCE4kL2DOM2dfh8BnhpcDmy4SHhNdPfh1QXPkkCoKDSQSr7Ar0OAxeAO7mrC5Y3+SNnuHATTtV0GZARZtJjMQEIwQIPWa5XZe4hc3ZcfinUf2qVwfF2WNVL9ExEW0gXDJFce8mODGGgu6CGtOQqbrFWAz5S2dxjBzlHEGSGhLdUKvlT5a9TnZoX5M32AJnMnVRzCE2YSVPNggHDMGnCjktbMZJ0=
    postgres-password: AgAq0vy68m1xLblHOME5Q1XdPsP+JJgdaBCzyXk0UkWv2w73EPLueNua2eGP6j4XSNKmZvlAp5DnejSHyWuT6D0zS5Hu23YBOiqPdmYfFtY3TdSklmxa677gmxLPRp45fztLKLQK3FZ4tAFR17/aeJnph9OIrEvgJz3ZYAhMX4UFEM1pL3I4jhAnS0sDe0uaC3aJCVGqAHKZhv9lxNKoncuUHWGxzxFpFPg0QdaXW82jNJDUpvXG+2NBAXdLecZolddQWRHM81bCPn2/7mn62MX8EkOhomFPaeGH2vdc0cYNBedrYolXFdPxtdC3X/1nnzMXAqnU+pC1gC/eAi0W4lgtc/WYcqQe0Z6c8dhOm56ciZXDRTkul81621rI1jqML74ewCM77fm8Wq40bodcHLkTVchxUOkbEDOulzmgoE00W48L5hT9qqtS01mV9vbpXUFcQOSS4G2sBYZJi1LxG1qiVIavurGMwqetFd/EmqmDCZNVv2mowTUhnGvOXcPOT53vyKFZUp6p00MVkcj6bPuOlQNYBKEPkVQQRqUyOlCodYeiYVukYunKd6CHkPyLycg4/MC16QhjsNRLVdyW2xNgn6ZC2tiVLJOunBK0KLNEtYi1jZFTtGlzSznw/sU8WDVvW6yhrq8psYtY5dyobjKr+rjT6bjfqBBZWkdCjSGidwVDJZNEmLWOLHbC2v7kByR12U2xSzTxazgxG49EBUD0g8BolLHZcQU=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-secret
      namespace: keycloak
