---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgA/PLGkO+5JUS58Pd24eSr6EI6p1XGy4BntoyhDDjuHh9BMZmCBgcbQIbTHII+ae+zODF6IkY+LpmvKVp5ovoAcgEVU7xDq7363NdeYoqV87lFBz2G8hPRfYFxelNt/cjPQnBIwAgQgiq3PdBwGm8nf/qnEXodhw6haMCzaPbqF70qcjOs9qLS+pNmfolxVf8i3UXspKKA+njMVLyRyEmzduuEKyKg7ZAGMWo0ShwYSbeMG+s87tuo9QnzN7x7B6t5aL0DfK2OpBSkhEo5zqwYvrYjaxxpJjrM34s9TW/6AkxxDqWpMwO9HMDH+i7ysUrpW2WUReEjLY2Lu0cERZG4wrihNJgFb0sY/uLlATixmFAerZ4z7gHfs0mmIb+TzLEoKZHWOQ7Cd7zc3oC4djPtra7Qw3HTWvOwOwsoEsLHRXSyQJDaDH6WxXJMlYYx31eQ51w4580+mpfPTfK0eO3eEAb4nnb5wENqIX1khZpC3m1k6w3/x/Z4mynqmFg08rKk/GoobXJYW5u/uQyRATWntui5UTc2MXA4mOFh1RabqQ0weMMxJ89VuK3jphFEvsqh/NY6sMU+WnuYxeKhznzN1LdyQQxFrvvPqwri5elSaCVwqDQPvaq32sO9WcjjsRxMK4JkH0Pi/ezvDfwnPC2/EVXnOuN/l94eZeo9quGMeagLvlvmMNS+wjuJZhZ6zeNQAJNYavZo4UfuNpfBaizS7cCRQdAnPaD0=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
    type: Opaque
