---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgCdmMbLQN0BDlKj90/eqZPRfpVevxe7fFFddEGJdwlIpj90Bj2W7lK778yhJzEeyP7AXNOfnsBK4sK6GgkJM7hVjx5m0RCh1HlcqCjKdLgSL5utRps0jgw+rHn3icvQ0ZqlvwLUzz1qH8mFH5szAZxwvXD6QRg4Sv/mM2E4Rt8FiZY44mbAufm+J/VFSROuutPjx4og8+UPqhv3+MGah1sbCP92GbGZjz792WMVsYMsYxt/7fPd5U2C7WuE3sk7zNQvxrJUnKWq/00XKuucZPoeoFv9Bb84yJMqUrDg2pseTPjXqtycfn6vgrmBy9kKO/EJmLeprzeXZVxFQs/1VuTeClJ/q3N28Ea+ydITXgUOigzBRDHK/vwLGI1CY5Qvg7Mnj/STj/PAEuyUTJiMqMcYT0fg1avufd6Qorfbfa1wdov7G7tw/YQwFHN8ZIPxYyiCdFwLz+wd8emH78vhNj0eiPcNQ80pcie8v/2jMyx0BiEva/H5N4hz8cZUPD9VokmxNKxRhUDc+A7Q3dqXAwtnqwwCbyhfm1i2Ev/q8qPSRlf1lRCNIWZXQx4YWHU7NCn7WgZOFF6qY4CWB6HVqdbiaAF1NSsXSMotregOVPUA73nR2vnDpb0WeahCs3C9bVtXqfkkacuHgD+VDs+oAWGwoXfWoHhcZFrVXIc3jGwTfy2jktPc1imBFRATkpkxmbBL6CjnmG2XteIgmlSnC5Qxf1wHb5sypnM=
    postgres-password: AgAuI7ng+Oan+0o5da7Pwlc+3bKQ6NAjjS4c3NXaPG+uTutvgSfIg3Aern9u4yuBwwpPgQDBgM6+eAMjevGRlZK81M2LADGOlJn59H/1Lso3XCaPfyuN257rZPopouRsrxZMMADzmjGR6J8ErkQQVx+zuWm0WyUoKG5znhbaLekP2Yz85dMslZtxlLAU+CdHLf6I+YKwnB6PcxR5Z1Vr/tV11N6PVzYTUhcrxMGcQ0oLYA+SfpWFq8RDhS6KzK0tJ4Z6fHdk1JZxQh2R16ZAKvOPEARqbYC/Yv7GkTVvMHKORFHVEU/u6gPAA5I8XQD6bq6jbIukYLCY9DwY16supwO60eo9wvLPvlx05kfXmx6FpMpqZ+WwcmnVD/TF0cVKZKZNgJMzD8RUwIztglT/3Et4E3ulAfn/GHw3Ntqq/yJTZEF3HZN9b5G2Hv1VagWfZQ4mHiKu+3VumnJWMiLaC6dMujaN8TAbt6WUJKN0GAJWqkPjrAIF8NvfHqznzbVbHiPXVS7Pf8M052lfmr0xU2MGwjEUZQ3X0vHR/LqpbevRg+fOHNy2+ZHheFerA/krgq995Vpk7Q2AaULxhDHQW46P2yyOdAnDSAJP1OezlxZ78R4t6TXyE697Hp+B5WWGbJu1+iTNH0o1+DSktENLWpje5jtQku2SMyMAvzxnhLhw8+ee0HXz+iAOnI8UmfyKZtwteVaESkM3dZ2/qKNSu2y0JOgA+kOt4M8=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-secret
      namespace: keycloak
