---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgAczGF3R/lNpHfsn0I0Oljt6UkIHjL5FZxIYw7LAIq+bLoO9E2MFbKT0iKCFrsgaD7kYVEn/OMdurFZ5rxbTLRLMWs50leHPgLPc443dSV4JHbsVRdLgzl8K52MqbJ/yYt2Q4MlnpBm4uoO+6c9BM5cFElvrfWmcAbQ4CvE5DdZPNmeqq1nMUVHA2Pvag8oVv3ybphlsMIwxmUS5kfbBTt5HpbjRFa90GlISWfkO8JBvML8P7SGNn0XJsKVNjaAgZKkwoRHYeW61mbMx+3ja2ISZ1pedP328kBPG5WV4t6lnaOjFQ5nXMkwOZGeW2jUuTzbkpHuxFqdCFAPV1j7OJDxD37THBDfDxBkWs/sQ49Xt22Z8BQZecmBwsLwNqFS/uuTNaOfezKqN+2LT2qFh/oKukOUuhWTy/GIqwBGcOp2rheZec40tBfKzTbRQW34xqqiGZeIZvTTBE/NYbsmucGqmcH7/HT64hObeK/bfsjBO3GcTyvAX5c1KtT3CBakejFXdiI8L64PLeDMy8RxKcPgc68rEuCsUbJVpKPRpzyma5mHJE0A3Su2bgDbAoulcVmkZFJmhCxVTxpmwZXchIMsFtSce+GiVaksYjQ2HePsdEC56Fa7Sx2+0KjJy+LX9f6au03ZBhBOJ/u+vGNzTZogrjmu4lLxD68L1oRSb3u98GALBfpCciRKeuJjNQs1xh1x3DPfN83x0Uy5/+jR8b+S1ZvZgyEQFp2jWj2KTXZeRg==
    postgres-password: AgBXsp5fZUJaeCLQ4GkRy2O8TNCcHGP84JWnwf2BNTvLaovywmJuHWqO093F66OMcyxArGDGtzDxRjSKhFmPSPbIf6imuhkasushArVIL2VfRsyMaJ/8dkNq5PfIvFHzm8+suiN7lJswaKg1bxlOVq3BX1ZY97KvT7Pquulc/tsR4ApH8eK2BahP0bJEFllonh6xz4zRUPPMUIqbUOZVYrC9kXjty8ohCNQ0SVnIjU26vjZFo9FY/U3b6uVLXE2ksmWGi5qYd+vu8tusKUUyWl5PCsYO7yeVLHilRzK+Z96lAZ8+rjJahtdONFlDrJ3N9WLqU7STRlXd4GPztpM9yH0g0dWsc1MxAsItT8P9gh3XWTn2+7LfaOzMrkaoH28eb4FAwxIWZFyIDGMuLQ0JoWfOctmv8hsqhtG+8QbNBwT5jLIzRUKsHIvPXJWbdJPjl1a4BbtfZmilfaT7TMeevlDK4gF/51CKNpdsoa1pybPZb3RRE6byZapX2DVLs2uU4o81xnX/0LrqMTXx7lOBxVPR9CtNQH6AmMsvT7BylIv2HbjtPlKOmQVkwCwqn27h8Fot4oSTm6hl+O/8e/oyMEiAZLukN5qGOBipxg6LnNQGI8jQRwaOBxGkc2RCLEccqkYmqEoSvNjeucW6XfH+z9n3KqfJrPtIsyM8YdWip7yy54kCHRCdpjNcsYSZsQQA4w+EL7KqMDrHgSsVTjst7pwRKDfYIJLfHlgVZUV9wKqEEQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-secret
      namespace: keycloak
