---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgCaQnD6oyXaQqcEFrdboCcY/JlWAfVePGUawDjXoYY3083Nan9nfqgUOVqjBeNzc5AlQ2jVT/8Bc1FmIUxBRCzaMhdf5KeiwGEv1+nRBUHsOBoFqLc2h0kahhtd9yEPynspq5OGzD0O8w5ckm2AVfLDY3P3LryHIoZku8sdPIMIDCnS3adrnJXoHDvCDGWwuuMJuVaHyTvNZo/8+9klAxBDOfe1vpgaVN/hQpbUNIt8Tt9s/RpiXG8qgBr8pN5wsp+AdA01szMUVqVn0DStQOKN9XwxoNhZi0RoWlcbbwxPHu8D5282gRgnzjzyN+L9eZwHYonCXuN8yNlxavJx4cuc0ao6CQq28+00jC8WPxcJPQhXK/mYVH4Suxmm6i/ri44Ql2syEAX2frItH/5pbDfMZuB/XrXipxYDkodE0DUoCDcx+ieQx7m4Md2uFCejqS3MML0SaImAKfGltGSgpKm/Nt0bSBxwGtcNOpTJeVq+HPhquAv6TS3yZL7o5AlXuIyahq7CbS+04REkVFgQ+NMO163oblRpR92Q6J0tSshsnu2U77xkZ2sTAQQlxcNMPfONjAXd7VpU1a0vDbrD+Tq1yz3KamZREhcqvrq5yxDEODClWYjkZCcg0gE2l+gJ29r/a9hW4HjRI7g8FISpWhaWYaex6Q4g6z0GAT98Pucpkjmoc1HBNlTUEnFWMOeOx7qGlMrkELpoVbwnhrZV6c4o9rDMA+ePQlEgfXsInlT3lQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
    type: Opaque
