---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgClOiBM36/WtzYsFTn9ttiuE6W50I0rPJopql/ebE6WLtEiYPYdt0D2oY4DbmhCVpZnZCQB0bnwNBF8qeguIQoypxpIYMW6bdx4Gg7o9LSMEzkLce8WWzgi8zOkStSwWjQMiBUO5rH0vjQ4gPacA/TEUZFfV0nXUv3J6ztXO0kp3G+mfpvXpOjpsz01BRTY9fLUTfrI+a2FyEuXOsEULc9mOx1q4Ha8RJGuf+8mkE5QR4PmGC9cAJfQNrPLZ/GX/quHA+vyYcVpSfYrDDuceG0xOtyjkY6H0yvSg3x/AAKUTKViHXJ6sUbSLBcFUgdd6qIuEMcuC6Roqw0WGL3MwOZLHVM0Xl3X5zl+WEIymhbDEUK92hUc691HTtNA0omb8EWErlE3ViA3M0tamyMS/LNtMH6QfLs2MEHX6MeiYJX8/J8EVImevnfkljufrAQHSa3sbJHUNcbs6D49U/gp39YgtRBr5YNu1e1hFewHtZIyclj3ZPFlA0TSmiHqDg/RCJuPU1bRHNcyP/cDYsUCSqTNxZiBLIiRA4GmFU4BmQMLh7OIoxdyair+F6L4S4Jn9Mj5f0CxB4K37rCOvNnHSTdXZC9dl1pUe0VYF2cmQyaehGaqkjTBWDvPsp1IJdrw9Jp825qOD1jsbRrmo20NIAXDoOlLaqlcrI2iQd3A4V3ZYT72adCFlmQQrtDDDbtJQDIP0Q2EhFgzbE1hWnvmTjvz7/pVhU8dzRc0n9Y7hjeDSQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
    type: Opaque
