---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgA6RRRLUJA+rK9+ErkOwfg3AwYPks40HBBc8QQkwY5TsjJaH03AYTzNm9vq73M6PG3WYaHtDT5OeM6/6GAOU66r6ZUypu1hPtrSfH8Uaubnpb8P/M14rYB0bY41ZTGL/qVPKFRxci6g1MwiTTj78Y0x/yCPmHkARiJhb4d7m62Xnu0+QBathcUfYYjs7ZTmRIICOnaDIXTXjGuZ/lYAAl3hzaPFGOeHQ1nIWD9V+VTcGmnCQKBJSy7dLDYXTWjEy5XoRLHUC9H2lrSXKkoknQkYofeybhVVj+zl4kin6w/Gt8oGyoYIPiokrFtN4yE6ERORPffjXhvMU18XE5XfsY4nescsletRe12R/YZRtTtBLpKpkC8aT86WdPWJcXTatPve89KXDuw03wejx0Mdo1aJgCHRElSktCV/50fTWQQbg8yRYuR4A0wdvJ8O9hjmVZVWpKaZ4SDw+PVzVwPR9v4JoAYKbFbrInxDaJUtyrTUnbc9iqIE0Ot1j4GotbcidJvZNzvYU3EVIeUD/2kviJgXpoHxznFO2ihjnp7WweI4fH7V1BZU6aukmoACO1ZK3NUDQB9Gkz8QFqEuUIJsINwLBJye+rUlThLYq+5o3mqnMEi0jxc4mwvCBj6jlD+K9i+bin9ujD6xi3dMjPeH71Kd+XwpnwszdvxBN2N6Tng4inFTBLT7bDVJyrEidmGtjv5s8Jw/CbecswD1d+PquyNeajArOofwDmI=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak
    type: Opaque
