---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBENJd7bnskYO34OR1oxV3BG2KVs6wNTg/RE2h7Z89P+Yo3Qtkcbma5qYz5oHeWGcmOoDM6zd/G7/eRE46clUe1s6TvWFyLVhdwjXHwncj3sJYZ5Ep+qFtgBgFveOt1Qm0mgVk88adFDLdwOWjZha2MEwWcHWgYmZJhzjGHiU1VPg/zVjLa4P8iAdZ3KqSn4qFmcDXhxi7+P7nU8aVEHfMiEzZOkKyTlRCgxR4xhsYWAqc+cCUkmecFP7G6MRZvF2REdpz1AyjBn9Yutf4K5mBs1rFz+N7jR7jIQLv+R7w18SuhBmmC3Oecm0KDrMwDwrejdkZpVmFy4qX/mASBtVQR6frh/6cBWiIiraEw07RARvn/brAt/mSZXQF7n5cPf2uvAFifmUGc9oCzofw2cdStexILk3eLaRzY60qQ7Kog0pO1qBfQQE+nu6Srk7fDnqJrZqFWPhaHIaKadgX5+AWRvmkm+UOazTeO7nPE5Clz6qh7KMmjB3Zfubdj2gE8pStIem/WP5e8fI0JmqWpXFxeBSOOJ5Av1Yx4Ooz2EwLLeEvzZ+QnYp5rA3oMOjU+A8AIHkGIrUYf98q/RepNzjYp7Qdzsvafkv7G1M3rgi6HJWzaQLDI+4zYJCUge6OnBPi4KxFEEKRCu83anfZlkHOXl/Er6vBemW1qrgFyC+A0N1oLx/rXTNuFCnYKlG+Bcq83inzoXf0bfwFxAXg6xIXkaAll3DDbrbv9O+aGcpdm9Q==
    postgres-password: AgDTxGBc5Rqto9Dfno5ivApWrkYua8KUyGofkWBsLTs7X6kUV4YLXNbBPnW89E7a66lt3WmbzRxu3vIRHp8Q75aEo+4KUDTslvP+1XdXU93AimyibZItqeZYy16nNnpFyYTlg5cc8wzNXGb4/Mgoo84GmiILLhup24t67QAH9SptF6ozKFnNcEIH0mvPqO7qHaHmRSpaO2tsEYLCfjaJ9U9lH8Cu9uNP2pa07CtaukeYqCdHWr+IWTELosM6EbGTM9zYbkbGMjoORLzUm6ZBkFPwzISNEy/QaSa1ea+nnMyObvhpl4LwY0HJ5ti/02p5NLSa8BwQcCGHQQuLgRN8kGolBGkAbIbR0wZWV6jTjPnSonKXOm0ey0+4IHs7e+gV65ocD9dtoJOJdMs9zorZk7dZONf5bEXk/2hrkGwotMiCE6X5rmuwrdXvKr/7oAf/9rxlirZOpyxMf/9G1cB8ZOy/KNK5emOV2jXiau254v8ZS6/KRH/7ucXRyS6tO2D/9lpDCLRD91jSrITtTmlI5B3DbfeNf2g4isgLEy7jO5DcMUDl9xTyjf/3efzqvCm6o/XxikbiThr6zQUQ21CEZnptkP9AGbY+RTx/Fn71JKcIRCDXVYXwcnoBbi1mVxt8mInJJUQw1hbMQKprvALqlfRI7SZ5vDOkagJ460DCddrqylBoCSsC0PNnb+ON8lhHUUi7tspvt6O4Bx6qysQ3UbYMSN58z46Z/de6ErFPLHkbFA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-secret
      namespace: keycloak
