---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA73cVUlGw+w/sLyBjwKkr36ITVIXSql35WZjVqKsNHBf3LWdwTmLTP/Wjf/FpudzbnxRcblb/sfoQS/3ujQmV2ZaJHvoG00l3s8XWaQk6lS8bQ/coG4Yuuz6Mq7bO2gSojg/sh/BPw1MXH2avs3PO1Zhu3GxOUFqk21zA31i2UnfCcESU7cZUdCG3bozfFmCTFAi/6mGtI4opDot72/r5nPuRs7nAJViQnacoOM+Omxhw66FDvh1cfBPH1NH/nzv3uErSL/tIuu0F5Vbh4a0B62k+94cegTd1orS01uXMqrJYd912SeWRj30gLkxlatggxlUd6KMmKxzPKJphovR1wAD/6cnxRNxlQK5SwgpNEUehcHGssxFjLDPLbT9COXXI7D0VbK3ZxUUU6VvUntkoSHzxe7fHFIUc2F6YF8wDavI7u7gdOp0L0f9IPGeqZDjapIINaxZ7M9HOTzuS0KEgF08k01yPvp0gvW/PogWw75Zg1DeFbBMJRyJTTKsDf/acc4sB8iHaKgRV2EZi9BrJ+UL8D8V5arrbF+s5Om7COMErvUOktXVS0ireerLSVBcaG2rgvhzi2W7w+F/gTv3DwKECUCXvWEjfdiI/WdNJL/A90rbC0Lq7NvCAyTXEVpGq7N5F7matG/8LhQYVoYmzat5l8v7iQWQXpBWvnoQ7/43dFha2GyvUkUsjYkBg3C0l8n0h2NhgGtKuG9yVz7ZV+sTEteOu2dp3pQcYlKZbLdg==
    admin-user: AgClsTfLom+IMmhA59Rxs6DfitprK/lBhv26QJLk48NK8e99B04HMaiHOPZLVadzMMDeNRe0RRMwXwRf96ZZE2NzLUetmusmtSeEYFoEd0CVEtRAynh4zbjEOY4hnXEReU2rR27HKME+VbjoU1t3Bll2cOSPuzGoiMnsCxrogBQhfLCZmgFCRHLH6kA94XeTvbpvz1c3RiTdJzQjmLXJdKnHGkJECt3Zlx+C5TC2j4L7mhjwSirjD3VO5DrBF8IfkIY/Yj2HisciOSHe9HzgxxRzIlI8UJkHahZJ6ovwTPkNRyYVLVT2cBRO0LZbOg6EVjNLMDfulSearzg5a+E85ifkWSdSaa5kmrxu+4NZdBM07pzyXawd0H7rdLLUooDPZpiXnYQrgVeWHBAqpf2pIGYpSS4ZGcJag0dRSH280+hKmoe93YA4uFCTpgh4pV9VvWoH46rKo4LcZjTaaJYg592bdTfa+58P2Iv65NhFe+KOApSUC90zlZ8YB1fHTRzysnQ0EvvkIGnbM/mPkvtE+3LH0N906BfFJRTV5L5uEC5M/+DHE6EPDtlP44ABe60af6o0+asRWSHPPLzDJ4iN0ahCgq09IT6NzycN/F5NuFF6igaR/NZGFYWxtB/7PLUPxgmFEc5bPmcp51ewYh/X37shyTj/H5nVwvyz4mrwEP6RyBNjUjBUQunb+PLH2VtEMEI9pZN9wA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
