---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '57.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 5m
  releaseName: prometheus
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    crds: 
      enabled: true
    prometheusSpec:
      retention: 2d
    grafana:
      admin:
        existingSecret: "grafana-admin"
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        path: /
        hosts:
          - grafana.glythium.io