---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-arc-controller-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  - name: sealed-secrets
  interval: 1h
  timeout: 5m
  targetNamespace: github-arc
  chart:
    spec:
      chart: actions/actions-runner-controller-charts/gha-runner-scale-set-controller
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: ghcr
      interval: 1h
  releaseName: controller-manager
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    nameOverride: controller-manager
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: "/metrics"