---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k3s-pi-5-runner
  namespace: flux-system
spec:
  dependsOn:
  - name: github-arc-controller-manager
  interval: 1h
  timeout: 5m
  targetNamespace: github-arc
  chart:
    spec:
      chart: actions/actions-runner-controller-charts/gha-runner-scale-set
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: ghcr
      interval: 1h
  releaseName: k3s-pi-5-runner
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    githubConfigUrl: https://github.com/Glythium/k3s-pi-5
    githubConfigSecret: runner-registration
    containerMode:
      type: "kubernetes"
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    # This block allows the worker Pods to use whatever ServiceAccount is defined in setup/runner-rbac.yaml's ConfigMap
    template:
      spec:
        serviceAccountName: github-arc
        securityContext:
          fsGroup: 123  # provides access to /home/runner/_work directory in ephemeral volume
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
                value: /home/runner/runner-pod-rbac-patch/default.yaml
            volumeMounts:
              - name: runner-pod-rbac-patch
                mountPath: /home/runner/runner-pod-rbac-patch
                readOnly: true
        volumes:
          - name: runner-pod-rbac-patch
            configMap:
              name: runner-pod-rbac-patch